// Hand-curated ambassador list: educators, program directors, and association
// leaders we ask to SHARE the conference with their students and members (not
// to sponsor it). Loaded into the database via Ambassadors -> "Load curated
// list"; each row gets a personal 20% discount code (unlimited uses, valid
// through August 10) whose redemptions are tracked per ambassador.
//
// Emails are published addresses found on the org's own pages (program pages,
// faculty directories, officer/contact pages) — search-sourced, so spot-check
// before a large send. The note is the personal "why we thought of you"
// paragraph in the engraved letter: individually written, verified facts only.

export type AmbassadorTarget = {
  org: string;
  contact: string;
  email: string;
  website: string;
  audience: string;
  note: string;
};

export const AMBASSADOR_TARGETS: AmbassadorTarget[] = [
  { org: "Dominican University — Medical Interpretation Certificate", contact: "", email: "chicago.admission@dom.edu", website: "https://www.dom.edu/academics/majors-programs/medical-interpretation-certificate", audience: "Spanish/English medical interpretation certificate students, Chicago area", note: "Your Medical Interpretation Certificate preps bilingual students for the national certification exams, and this conference is essentially in their backyard: a healthcare language-access gathering hosted with Lurie Children's in Chicago, with a virtual option. For students building medical terminology, ethics, and cultural competency skills, two days among working healthcare interpreters and hospital language-access leaders is a powerful complement to coursework." },
  { org: "UIUC — Program in Translation and Interpreting Studies", contact: "", email: "translation@illinois.edu", website: "https://translation.illinois.edu/", audience: "MA, certificate, and graduate minor T&I students, Illinois", note: "Your students train in a serious program with real interpreting booths and faculty across many languages, and healthcare is one of the fastest-growing settings where they will actually work. This conference at Lurie Children's puts them in the room with hospital language-access teams in their own state, and the virtual option keeps it affordable." },
  { org: "Madison College — Healthcare Interpreting Program", contact: "Jenn Sheppard", email: "jsheppard6@madisoncollege.edu", website: "https://madisoncollege.edu/academics/professional-continuing-education/healthcare-interpreting", audience: "Spanish/English healthcare interpreting certificate students, south-central Wisconsin", note: "Your two-semester program already carries students through the 40-hour training required for the CCHI exam, and a healthcare language-access conference at a children's hospital is a natural next step for them. Chicago is a short trip from Madison, and the virtual option works for students who cannot travel." },
  { org: "UW-Milwaukee — Translation and Interpreting Studies", contact: "Lorena Terando", email: "terando@uwm.edu", website: "https://uwm.edu/translation-interpreting-studies/", audience: "graduate translation and interpreting students, Milwaukee and online", note: "Your graduate students in Translation and Interpreting Studies are exactly who this conference serves: it is a healthcare language-access event hosted with Lurie Children's in Chicago, about 90 minutes down the road. They will hear directly from interpreters, clinicians, and language-access leaders working in pediatric care, a setting where demand for skilled spoken-language interpreters keeps growing." },
  { org: "Viterbo University — Community Interpreting Certificate", contact: "Michelle Pinzl", email: "mmpinzl@viterbo.edu", website: "https://www.viterbo.edu/english-spanish-and-world-languages-department/community-interpreting-certificate", audience: "online community interpreting certificate students, Wisconsin and beyond", note: "Your certificate's seminar on interpreting in medical and social settings maps directly onto what this conference is about: real-world healthcare language access, explored at a children's hospital in Chicago. Because your courses run online, the virtual track fits your distance students while Midwest students can attend in person." },
  { org: "Milwaukee Area Technical College — Medical Interpreter Technical Diploma", contact: "", email: "healthpathway@matc.edu", website: "https://www.matc.edu/course-catalog/healthcare/medical-interpreter.html", audience: "bilingual Spanish/English medical interpreter students, Milwaukee", note: "Your bilingual technical diploma trains students to facilitate communication between patients and medical personnel, and this conference lets them see that work at scale inside a major children's hospital. It is an easy trip from your Downtown Milwaukee campus, with a virtual option too." },
  { org: "Johnson County Community College — Health Care Interpreting Certificate", contact: "Christina Wolff", email: "cdecasqu@jccc.edu", website: "https://www.jccc.edu/academics/credit/health-care-interpreting/", audience: "Spanish/English health care interpreting cohort students, Kansas City metro", note: "Your selective program builds exactly the interpreters this conference was created for, and a small cohort makes it easy to bring everyone along. The event pairs a children's hospital setting with practical language-access content, and the virtual option means your evening students can join without leaving Kansas City." },
  { org: "Kent State University — Translation Programs", contact: "Brian Baer", email: "bbaer@kent.edu", website: "https://www.kent.edu/mcls/translation-programs", audience: "BS and MA translation students, Ohio and online", note: "Kent State translation students increasingly land in healthcare, where language access is both a legal requirement and a patient-safety issue, and this conference shows them that side of the profession up close. It is hosted with Lurie Children's in Chicago, with a virtual option that suits your online MA students." },
  { org: "UMass Amherst — Online Certificate in Professional Translation and Interpreting", contact: "Cristiano Mazzei", email: "cmazzei@umass.edu", website: "https://www.umass.edu/languages-literatures-cultures/academics/online-certificate-professional-translation-interpreting", audience: "online translation and interpreting certificate students nationwide", note: "Your online certificate includes medical interpreting coursework, and this conference gives those students a live view of healthcare language access inside a children's hospital. Because the event runs both in Chicago and virtually, your distance students anywhere in the country can join." },
  { org: "Hunter College Continuing Education — Certificate in Medical Interpreting", contact: "", email: "ce@hunter.cuny.edu", website: "https://continuing-ed.hunter.cuny.edu/certificate-in-medical-interpreting-in-new-york-city/", audience: "medical and community interpreting certificate students, New York City", note: "Your Certificate in Medical Interpreting draws bilingual New Yorkers heading straight into hospital and community work, and this conference extends that training with a national view of healthcare language access. The virtual track fits continuing education students perfectly." },
  { org: "NYU School of Professional Studies — MS in Translation and Interpreting", contact: "Annelise Finegan", email: "sps.translation@nyu.edu", website: "https://www.sps.nyu.edu/explore/degrees-and-programs/ms-in-translation.html", audience: "online MS in translation and interpreting students worldwide", note: "Your fully online MS students are building professional portfolios, and healthcare is one of the most mission-driven and fastest-growing specializations open to them. This language-access conference at a children's hospital offers a virtual option, so your asynchronous learners can attend from anywhere." },
  { org: "Bunker Hill Community College — Medical Interpreter Program", contact: "Katherine Lopez", email: "kl249702@bhcc.edu", website: "https://www.bhcc.edu/workforce/career/medicalinterpreterprogram/", audience: "multilingual medical interpreter trainees, greater Boston", note: "Your program trains interpreters in Spanish, Portuguese, Arabic, and Mandarin with real hospital partnerships, so a conference on healthcare language access at a children's hospital is a natural fit for your graduates. The virtual option works well for your remote-instruction students." },
  { org: "Howard Community College — Health Care Interpreter Certificate", contact: "", email: "HCIT@HowardCC.edu", website: "https://www.howardcc.edu/programs-courses/continuing-education/courses/health-care-careers/health-care-interpreter-certificate/", audience: "health care interpreter certificate students, Maryland and DC area", note: "Your certificate takes students from orientation through supervised field experience, and this conference adds the national conversation on healthcare language access to that journey. The virtual option fits your hybrid evening-and-Saturday students well." },
  { org: "UNC Charlotte — Translating and Interpreting Programs", contact: "Christopher Mellinger", email: "cmelling@charlotte.edu", website: "https://languages.charlotte.edu/", audience: "undergraduate and graduate T&I students, Charlotte and online", note: "Your T&I students, especially in the Spanish-English track, will spend much of their careers in medical settings, and this conference shows them what strong hospital language access looks like from the inside. The virtual option covers students who stay in Charlotte." },
  { org: "Wake Forest University — Interpreting and Translation Studies", contact: "Olgierda Furmanek", email: "furmano@wfu.edu", website: "https://interpretingandtranslation.wfu.edu/ma-in-interpreting-and-translation-studies/", audience: "MA interpreting and translation students, Winston-Salem and online", note: "Your MA students train across Spanish, Chinese, and English, and healthcare interpreting is where that range meets urgent community need. This language-access conference at a children's hospital also offers a virtual track, so both campus and online students can take part." },
  { org: "City College of San Francisco — Healthcare Interpreting Certificate", contact: "", email: "hci@ccsf.edu", website: "https://www.ccsf.edu/degrees-certificates/healthcare-interpreting", audience: "multilingual healthcare interpreting certificate students, San Francisco Bay Area", note: "Your certificate has been preparing linguistically and culturally competent healthcare interpreters since 1997, with graduates in a dozen languages, and this conference speaks directly to that mission. The virtual option means your Bay Area students can join without travel." },
  { org: "American River College — Healthcare Interpreting Certificate", contact: "Yeny Lopez", email: "askhb-healthed@arc.losrios.edu", website: "https://arc.losrios.edu/academics/programs-majors/healthcare-interpreting", audience: "multilingual healthcare interpreting certificate cohorts, Sacramento region", note: "Your language cohorts are built around real community need, which is exactly the spirit of this conference on healthcare language access hosted with Lurie Children's. The event pairs a children's hospital setting with practical sessions for working and student interpreters, and the virtual track keeps it accessible from Sacramento." },
  { org: "UC San Diego Extended Studies — Translation and Interpretation (Spanish/English)", contact: "", email: "ahl@ucsd.edu", website: "https://extendedstudies.ucsd.edu/certificates/translation-and-interpretation-(spanish-english)", audience: "online Spanish/English translation and interpretation certificate students", note: "Your certificate includes a medical interpretation course covering patient-provider communication, ethics, and the interpreter's role in healthcare, and this conference brings all of that to life at a children's hospital. The virtual option suits your fully online students." },
  { org: "Columbia College Chicago — ASL-English Interpretation BA", contact: "Diana Gorman Jamrozik", email: "dgorman@colum.edu", website: "https://www.colum.edu/academics/programs/asl-english-interpretation", audience: "ASL-English interpreting BA students, downtown Chicago", note: "Columbia trains ASL-English interpreters right in downtown Chicago, a short ride from Lurie Children's. A conference where ASL access is a first-class theme, set in a children's hospital context, gives your BA students a rare early look at pediatric healthcare interpreting. Student pricing and a virtual option make it easy for a whole cohort to come." },
  { org: "College of DuPage — ASL Interpreting AAS & Certificate", contact: "Adam Wasilewski", email: "wasilewskia54@cod.edu", website: "https://www.cod.edu/academics/areas/american-sign-language-interpreting/index.html", audience: "ASL interpreting students, western Chicago suburbs", note: "Your students at COD are exactly who healthcare interpreting needs next. Two days on language access in a children's hospital setting, with ASL access treated as a first-class theme, would show them where their skills lead. Chicago is right up the road, and the virtual track fits community college schedules." },
  { org: "Harper College — ASL & Sign Language Interpreting", contact: "Marcos Aguilar", email: "am24646@harpercollege.edu", website: "https://www.harpercollege.edu/academics/liberal-arts/world-languages/asl/faculty.php", audience: "ASL and interpreting students, northwest Chicago suburbs", note: "Harper's ASL program reaches interpreting students across Chicago's northwest suburbs, an easy trip to the conference. Sessions on signed and spoken language access in pediatric care map directly onto the settings your graduates will work in, and the student code plus a low-cost virtual option keeps it within reach." },
  { org: "Moraine Valley Community College — ASL Deaf Studies & Interpretation", contact: "Shelley Engstrom-Kestel", email: "engstrom-kestels@morainevalley.edu", website: "https://www.morainevalley.edu/academics/academic-programs/communicationsliteratureforeign-languages/sign-language-interpretation/", audience: "Deaf studies and interpreting students, southwest Chicagoland", note: "Moraine Valley pairs a Deaf Studies foundation with a selective interpretation program, so your students arrive already invested in the Deaf community. A healthcare conference with ASL access as a first-class theme, held at a children's hospital across town, is a natural next step for them, and CEU-eligible sessions add value for working alumni too." },
  { org: "Southwestern Illinois College — Sign Language Studies / Interpreter Training", contact: "Susen McBeth", email: "Susen.McBeth@swic.edu", website: "https://www.swic.edu/academics/career-degrees/arts-and-communication/sign-language/contact/", audience: "Interpreter training students, Metro East / St. Louis region", note: "SWIC prepares sign language interpreters for the Metro East and greater St. Louis region, where healthcare assignments are steady work. The conference pairs ASL access with spoken language access in a children's hospital context, mirroring the care teams your graduates will join, and virtual registration makes the distance a non-issue." },
  { org: "Illinois Central College — Interpreter Preparation AAS & Certificate", contact: "Katie Moore", email: "katherine.moore@icc.edu", website: "https://icc.edu/academics/catalog/career-degrees-certificates/health-careers/american-sign-language-english-interpreting/", audience: "Interpreter preparation students, central Illinois", note: "Illinois Central lists interpreter preparation among its health careers programs, so a healthcare language access conference is squarely on mission. Your students would see pediatric settings where ASL access is built in as a first-class part of care rather than an afterthought, and virtual access keeps it easy from Peoria." },
  { org: "RIT / NTID — ASL and Interpreting Education", contact: "Jason Listman", email: "info-ASLIE@rit.edu", website: "https://www.rit.edu/ntid/aslie", audience: "ASL-English interpreting BS students at NTID", note: "NTID's ASL and Interpreting Education department sits inside one of the largest Deaf student communities in the country, and its graduates routinely move into medical interpreting. A conference built around both signed and spoken language access in a children's hospital setting extends exactly what ASLIE teaches, and virtual attendance makes Rochester to Chicago a non-issue." },
  { org: "UNC Greensboro — Interpreting, Deaf Education, and Advocacy Services BS", contact: "Samuel Parker", email: "sdparker@uncg.edu", website: "https://www.uncg.edu/degrees/interpreting-deaf-education-and-advocacy-services-b-s/", audience: "Interpreting and Deaf education undergraduates, North Carolina", note: "UNCG's interpreting program prepares interpreters for community settings including healthcare, and your students take certification seriously. This conference shows them pediatric language access done well, and CEUs plus a virtual track make it worthwhile for alumni and faculty alike." },
  { org: "St. Catherine University — ASL and Interpreting Department", contact: "Aimee Sever-Hall", email: "asl@stkate.edu", website: "https://www.stkate.edu/academics/shas/asl-interpreting-department", audience: "ASL interpreting students, Twin Cities", note: "St. Kate's ASL and Interpreting department is home to the CATIE Center, which leads national ASL interpreting education initiatives. Your students would find a children's hospital conference with first-class ASL access directly relevant to where the field is heading, and the virtual option works well from the Twin Cities." },
  { org: "UW-Milwaukee — ASL/English Interpreting BS", contact: "Catherine J. Giuntoli-DuBois", email: "giuntolc@uwm.edu", website: "https://uwm.edu/education/community-engagement/asl-enrichment-center/", audience: "ASL and interpreting students, Wisconsin", note: "UWM offers Wisconsin's only four-year bachelor's program in ASL/English interpreting, and its ASL Enrichment Center is staffed entirely by Deaf individuals. Healthcare interpreting is a natural landing spot for your graduates, and Milwaukee is about 90 minutes away, close enough for the in-person weekend." },
  { org: "Illinois State University — Communication Sciences and Disorders", contact: "Heidi Verticchio", email: "hrfritz@IllinoisState.edu", website: "https://csd.illinoisstate.edu/", audience: "SLP and audiology students, central Illinois", note: "Illinois State's CSD department sends waves of new SLPs into Illinois schools and hospitals. Pediatric communication access in a children's hospital setting is the daily work many of your students are headed toward, and student pricing plus a virtual option fits budgets in Normal." },
  { org: "Northern Illinois University — Speech-Language Pathology", contact: "", email: "niuslp@niu.edu", website: "https://www.chhs.niu.edu/ahcd/programs/slp/index.shtml", audience: "SLP students, northern Illinois", note: "NIU trains speech-language pathologists an hour from Chicago, many of whom will serve multilingual and Deaf families. A conference that treats ASL access and spoken language access as one conversation fills a gap most SLP curricula leave open, and CEU-eligible sessions add value for clinical faculty and supervisors too." },
  { org: "UIUC — Department of Speech and Hearing Science", contact: "", email: "shs@illinois.edu", website: "https://shs.illinois.edu/", audience: "Speech and hearing science students, Illinois flagship", note: "Illinois' flagship Speech and Hearing Science department reaches undergraduates and graduate clinicians from across the state. Language access in pediatric care, with interpreters and clinicians learning in the same room, is a perspective your students rarely get in coursework, and the virtual track makes it easy from Champaign." },
  { org: "Northwestern University — Communication Sciences and Disorders", contact: "", email: "csd@northwestern.edu", website: "https://communication.northwestern.edu/academics/communication-sciences-and-disorders/", audience: "CSD and SLP graduate students, Evanston and Chicago", note: "Northwestern's Pepper Department sits just up the lake from Lurie Children's, and its SLP graduate students train for exactly these pediatric settings. A conference where ASL access and spoken language access share the main stage complements their clinical education, and in-person attendance is an easy trip from Evanston." },
  { org: "UIC College of Medicine — Clinical Medical Spanish Elective", contact: "Maria Isabel Angulo", email: "angulo@uic.edu", website: "https://chicago.medicine.uic.edu/education/md-curriculum/curriculum-by-year/phase-2-3/electives-and-pathway-structure/electives-catalog/clinical-medical-spanish/", audience: "UIC medical students in clinical Spanish training", note: "Your Clinical Medical Spanish elective trains medical students to care for Spanish-speaking patients safely. This conference puts those students in the room with the interpreters and language access leaders they will work alongside, in a children's hospital in their own city, and student pricing makes it a natural add to the elective." },
  { org: "DePaul University — Spanish for Health Care", contact: "Maria Luisa Ortega Hernandez", email: "mlortega@depaul.edu", website: "https://www.depaul.edu/faculty/maria-luisa-ortega-hernandez", audience: "Spanish for health care students, Chicago", note: "You developed Spanish for Health Care courses and serve with the National Association of Medical Spanish, so language access is already your classroom's heartbeat. Your DePaul students would hear directly from healthcare interpreters and clinicians working in a children's hospital context, in their own city, with a virtual option for commuter students." },
  { org: "Saint Louis University — Spanish for the Health Professions", contact: "", email: "languages@slu.edu", website: "https://www.slu.edu/arts-and-sciences/academics/degrees/undergraduate/spanish-ba.php", audience: "Spanish for the health professions students, St. Louis", note: "SLU's Spanish program runs a dedicated Spanish for the Health Professions course sequence with real clinic exposure. Students on that track would get a working picture of hospital language access, spoken and signed, from the people doing it every day, and virtual registration keeps the trip optional." },
  { org: "University of Cincinnati College of Medicine — Medical Spanish / Latino Health Elective", contact: "Christy O'Dea", email: "Christine.odea@uc.edu", website: "https://med.uc.edu/depart/familymed/medical-education/first-second-year", audience: "Medical students in a longitudinal Latino health elective, Cincinnati", note: "Your Medical Spanish and Latino Health elective is a multi-year commitment, so these students have already made language access part of their identity as future physicians. A children's hospital conference with CEU-bearing sessions and a virtual track extends that commitment beyond Cincinnati." },
  { org: "CHICATA — Chicago Area Translators and Interpreters Association", contact: "Jane Hu", email: "President@chicata.org", website: "https://chicata.org/about", audience: "Chicago-area professional translators and interpreters", note: "Your members are the exact community this conference was built for, and it is happening in their own city with sessions on healthcare language access. Many CHICATA members already work in medical settings or want to move into them, and the in-person days in Chicago plus a shareable discount make this an easy, affordable professional development win to pass along." },
  { org: "MATI — Midwest Association of Translators and Interpreters", contact: "Reme Bashi", email: "MATIemail@gmail.com", website: "https://www.matiata.org/", audience: "Translators and interpreters across Illinois, Wisconsin, Indiana", note: "MATI's footprint covers the exact region this conference serves, with Chicago an easy trip for most of your members and a full virtual option for everyone else. A healthcare language-access program hosted with Lurie Children's speaks directly to the medical interpreters and translators in your membership." },
  { org: "MICATA — Mid-America Chapter of the American Translators Association", contact: "", email: "micata@gmail.com", website: "https://micata.org/", audience: "Translators and interpreters in the Kansas City and Mid-America region", note: "For your members who work in medical and community settings, this two-day healthcare language-access conference offers a national-caliber program without national-conference travel: the full event streams virtually, and Chicago is a short hop for anyone wanting the in-person days. A shareable discount code makes it an easy benefit to pass along in your next member email." },
  { org: "UMTIA — Upper Midwest Translators and Interpreters Association", contact: "", email: "info@umtia.org", website: "https://www.umtia.org/", audience: "Translators and interpreters in Minnesota and the Upper Midwest", note: "Healthcare work is a major part of interpreting in the Twin Cities, and this Lurie Children's and AALB conference is entirely focused on language access in healthcare. Your members can join virtually or make the trip to Chicago, and we would be glad to give UMTIA members a discount to share." },
  { org: "NOTIS — Northwest Translators and Interpreters Society", contact: "", email: "info@notisnet.org", website: "https://www.notisnet.org/Contact-us", audience: "Translators and interpreters in the Pacific Northwest", note: "For NOTIS members working in medical interpreting, this conference brings together clinicians and language professionals around healthcare language access, and the virtual registration means no one has to leave the Northwest to attend. We are happy to send a ready-to-post blurb for your communications channels." },
  { org: "CHIA — California Healthcare Interpreting Association", contact: "", email: "info@chiaonline.org", website: "https://www.chiaonline.org/", audience: "Healthcare interpreters across California", note: "CHIA's whole mission is healthcare interpreting, so this two-day conference with Lurie Children's is about as on-target for your members as an event can be. The virtual track makes it accessible from anywhere in California, and a discount code for CHIA members would let you pass along real value in a single newsletter mention." },
  { org: "OHCIA — Oregon Health Care Interpreters Association", contact: "", email: "support@ohcia.org", website: "http://ohcia.org/contactus", audience: "Healthcare interpreters and interpreter trainees in Oregon", note: "Your interpreters and students live this work every day, and this conference is devoted specifically to language access in healthcare, co-hosted by Lurie Children's in Chicago. With full virtual access and a discount for your community, it is an affordable way for Oregon interpreters to learn alongside clinicians and language-access leaders nationally." },
  { org: "WASCLA — Washington State Coalition for Language Access", contact: "", email: "info@wascla.org", website: "https://wascla.org/about-us/contact-us/", audience: "Interpreters, providers, and language-access advocates statewide in Washington", note: "WASCLA brings together exactly the mix of interpreters, providers, and advocates this conference is designed for. The program centers on language access in healthcare and streams virtually on August 15 and 16, and we would be glad to give your coalition a discount code to circulate to members working on health language access across Washington." },
  { org: "ATA Medical Division — Caduceus newsletter", contact: "", email: "caduceusnewsletter@ata-md.org", website: "https://ata-md.org/contribute-to-caduceus/", audience: "Medical translators and interpreters nationwide", note: "Caduceus readers are medical translators and interpreters, precisely the professionals this healthcare language-access conference serves. A short mention with a member discount would give your readers an affordable option, virtual from anywhere or in person in Chicago, and we are happy to supply copy sized to your format." },
  { org: "ATA Interpreters Division", contact: "Daniela E. Obregón", email: "DivisionID@atanet.org", website: "https://www.ata-divisions.org/ID/about/leadership-council/", audience: "Interpreters nationwide across specialties", note: "Many of your division members interpret in healthcare or are building toward it, and this Lurie Children's and AALB conference is focused entirely on language access in that setting. With a virtual rate and a discount for your members, it is a low-cost, high-relevance item for your blog or member communications, and we can provide ready-made text." },
  { org: "UIC School of Public Health — Community Health Sciences", contact: "Jeni Hebert-Beirne", email: "jheber1@uic.edu", website: "https://publichealth.uic.edu/profiles/jeni-hebert-beirne/", audience: "UIC public health students and community-engaged health equity researchers", note: "Language access is one of the most concrete health equity issues your students encounter in Chicago community work, and this conference puts them in the room with the clinicians and interpreters solving it, blocks from campus. The student-friendly rates and a discount code for your students and colleagues make it easy to share." },
  { org: "DePaul University — Master of Public Health program", contact: "John Mazzeo", email: "jmazzeo@depaul.edu", website: "https://www.depaul.edu/faculty/john-mazzeo", audience: "DePaul MPH students in community health practice", note: "Your MPH students focused on community health would get a rare, close-up look at how a major children's hospital and community language professionals tackle language access, right here in Chicago on August 15 and 16. With a student discount it is a realistic add-on to their summer, and a strong networking room for practicum leads." },
  { org: "Loyola University Chicago — Parkinson School, MPH Program", contact: "Nallely Mora", email: "namora@luc.edu", website: "https://www.luc.edu/parkinson/ourpeople/facultystaffprofiles/nallelymorafaculty.shtml", audience: "Loyola MPH and public health sciences students", note: "For MPH students interested in health equity, this conference makes language access tangible: two days with interpreters, clinicians, and health-system leaders, co-hosted by Lurie Children's in Chicago on August 15 and 16. The virtual option fits student budgets, and we would love to offer your students and faculty a discount code you can share directly." },
  { org: "Northwestern Feinberg — Center for Bioethics and Medical Humanities", contact: "Bryan Morrison", email: "bryan-morrison@northwestern.edu", website: "https://www.bioethics.northwestern.edu/about/contact-us.html", audience: "Medical humanities and bioethics graduate students and faculty", note: "Language access sits squarely at the intersection of ethics, communication, and equity that your MA students study, and this conference turns it into two days of concrete cases from a major children's hospital and working interpreters. It happens August 15 and 16 just up the road in Chicago, with a virtual option and a discount for your students and faculty." },
  { org: "UIC College of Medicine — Hispanic Center of Excellence", contact: "", email: "hcoe@uic.edu", website: "https://medicine.uic.edu/hcoe/contact-hcoe/", audience: "Latino medical students and pre-health pipeline students at UIC", note: "Your students are heading into exactly the clinical encounters this conference is about: caring for families across languages. Sessions on healthcare language access, hosted with Lurie Children's here in Chicago, would show them how interpreters and bilingual clinicians work as a team, and the student discount keeps it accessible." },
  { org: "UIC School of Public Health — Public Health Student Association", contact: "", email: "PHSA.uic@gmail.com", website: "https://publichealth.uic.edu/current-students/student-organizations/public-health-student-association/", audience: "All UIC School of Public Health students", note: "This is a conference your members can actually attend: it is in Chicago on August 15 and 16, has a discounted student-friendly rate with your code, and tackles language access, one of the most visible equity gaps in Chicago healthcare. It is also a friendly room for students to meet interpreters, clinicians, and health-system leaders working on the problem." },
];
