// Hand-curated starter prospect list for the bulk sponsor/exhibitor inviter.
// These are web-verified, fresh targets with a real published contact email.
// Intentionally LEFT OUT: already-confirmed sponsors (e.g. LanguageLine, paid)
// and orgs tied to confirmed speakers (Equiti/Alonzo, Tica/Will, NCIHC/Speroff),
// which are warm relationships to handle personally, not cold invites.
//
// The note is the per-org body of the invitation email: a genuinely tailored
// few sentences about why THIS org fits a children's-hospital language-access
// conference. It is the bulk of the email, not a single line. Edit freely.
// Tab-delimited so commas inside notes stay safe.

type Target = [company: string, contact: string, email: string, website: string, note: string];

const TARGETS: Target[] = [
  ["CyraCom", "", "getstarted@cyracom.com", "https://www.cyracom.com", "CyraCom's healthcare interpreting is already in the hospitals our attendees staff every day, so the exhibitor floor puts you face to face with the interpreters, language-services managers, and clinicians who actually use it. Hosted by a children's hospital, this conference gathers the pediatric and family-care teams who feel language barriers most acutely. We'd be glad to have CyraCom in the room."],
  ["AMN Healthcare Language Services", "", "lscs@amnhealthcare.com", "https://www.amnhealthcare.com/language-services/", "As an official AALB partner, AMN already stands with us, so this is less an introduction than an invitation to be in the room as the partner you are. Your video interpreting is a daily lifeline for the medical interpreters and hospital leaders this conference convenes, and a children's-hospital setting brings the pediatric teams and families where getting language right matters most. We'd love to have AMN exhibit and be recognized alongside us."],
  ["Propio Language Services", "Lisa Stokesbury", "lstokesbury@propio.com", "https://propio.com", "Propio has become one of the largest forces in healthcare interpreting, and our attendees are exactly the interpreters, agencies, and hospital buyers your growth depends on. As a children's-hospital conference on language access, we convene the people shaping how care reaches limited-English families. We'd be glad to have Propio exhibit and help set the tone for what comes next."],
  ["MasterWord Services", "", "info@masterword.com", "https://www.masterword.com", "MasterWord's training and language services are exactly what the interpreters and hospital partners at this conference come to find, and your work in healthcare is well known to this community. Hosted by a children's hospital, we draw the pediatric and family-care teams who live language access every day. We'd love to have MasterWord exhibit with us."],
  ["Wordly", "", "contact@wordly.ai", "https://www.wordly.ai", "Wordly sits right at the 'Tomorrow' in our theme, and there's a real opportunity on two fronts: an exhibitor presence in front of a national healthcare-interpreting audience, and powering live translation for the conference itself. As a children's-hospital event, we're focused on reaching every family in their own language. We'd love to explore both with you."],
  ["Jeenie", "", "support@jeenie.com", "https://jeenie.com", "Jeenie's on-demand model speaks straight to the 'Tomorrow' side of our theme, and the interpreters and hospital teams at this conference are exactly the community you're building for. Hosted by a children's hospital, we gather the pediatric and family-care professionals who feel language gaps first. We'd be glad to have Jeenie exhibit and meet them."],
  ["Gallaudet University", "", "sponsorship@gallaudet.edu", "https://gallaudet.edu", "Deaf and ASL access is core to true language access, and Gallaudet's presence would mean a great deal to the interpreters, clinicians, and advocates at this conference. As a children's-hospital event, we're thinking about Deaf children and families as much as spoken-language ones. We'd love to have Gallaudet exhibit and introduce your programs to a national audience."],
  ["CCHI", "", "admin@cchicertification.org", "https://cchicertification.org", "So many of our attendees hold CCHI certification that the conference is essentially your community in one room: the healthcare interpreters and trainers who built their careers on your credential. Hosted by a children's hospital, it centers the pediatric and family-care settings where certified interpreting matters most. We'd love to have CCHI exhibit and connect with them directly."],
  ["IMIA", "", "outreach@imiaweb.org", "https://www.imiaweb.org", "IMIA's membership and our attendees are largely the same people, the medical interpreters working at the front lines of language access, so an exhibitor table puts you face to face with your community. As a children's-hospital conference, we draw the pediatric teams and families who depend on skilled interpreting. We'd be glad to have IMIA join us."],
  ["American Translators Association", "Chelsey Sleeter", "sponsorship@atanet.org", "https://www.atanet.org", "The ATA's healthcare-interpreting community overlaps heavily with our attendees, and your structured sponsor program tells us you value being in rooms like this. Hosted by a children's hospital, we gather the pediatric and family-care interpreters and clinicians at the center of language access. We'd love to have the ATA exhibit with us."],
  ["Registry of Interpreters for the Deaf", "", "communications@rid.org", "https://rid.org", "For the Deaf-access side of this conference, RID's presence would be invaluable, since your members are the ASL interpreters our attendees work alongside every day. As a children's-hospital event, we're focused on Deaf children and families as much as anyone. We'd love to have RID join us on the floor."],
  ["Tarjimly", "", "yassin@tarjim.ly", "https://www.tarjimly.org", "Tarjimly's work connecting refugees and immigrants with interpreters is the very heart of what this conference is about. Hosted by a children's hospital, we see how language access changes outcomes for immigrant and refugee families and their children. We'd love to have Tarjimly exhibit and share your mission with this audience."],

  // Pediatric / children's angle (this is a children's-hospital conference).
  // Web-verified contacts only; the big children's brands (Abbott, Enfamil,
  // Medela, WTTW, Ronald McDonald House) are relationship/form-only and live
  // in the separate creative-targets file for manual outreach, not here.
  ["American Academy of Pediatrics", "", "ksamp@aap.org", "https://www.aap.org", "As the home of American pediatrics, and practically our neighbor in Itasca, the AAP belongs at a children's-hospital conference on language access. Your own policy work on immigrant child health and language services speaks directly to our theme. We'd be honored to have the AAP exhibit or partner with us."],
  ["Sesame Workshop", "", "Partnerships@sesame.org", "https://sesameworkshop.org", "Few organizations have done more for immigrant and refugee children in their own languages than Sesame Workshop, and that mission is the spirit of this conference. Hosted by a children's hospital, we gather the clinicians, interpreters, and advocates serving exactly those families. We'd love to explore having Sesame Workshop join us as a partner."],
  ["Reach Out and Read", "", "info@reachoutandread.org", "https://reachoutandread.org", "Reach Out and Read already lives where this conference does, inside the pediatric visit, putting books into families' hands in dozens of languages. As a children's-hospital event on language access, the fit is genuine and meaningful. We'd love to have you in the room and to explore a partnership."],
  ["Lee & Low Books", "", "sales@leeandlow.com", "https://www.leeandlow.com", "As the leading publisher of bilingual and multicultural children's books, Lee & Low would be a natural and welcome presence at a children's-hospital conference on language access. Our attendees, who serve multilingual families every day, would truly value your titles. We'd love to have you exhibit with us."],
  ["Children's Hospital Association", "", "memberservices@childrenshospitals.org", "https://www.childrenshospitals.org", "Lurie Children's is one of your members, and language access is a shared priority across every children's hospital the CHA represents. This conference convenes the pediatric language-access community your members rely on. We'd be glad to have the CHA partner with us and reach that audience."],
  ["La Rabida Children's Hospital", "Anne Mullen", "amullen@larabida.org", "https://larabida.org", "As a fellow Chicago children's hospital serving so many Medicaid and multilingual families, La Rabida is a natural ally for this conference. The families you care for are exactly who our work is about. We'd love to have La Rabida exhibit or join us as a community partner."],
  ["Family Voices", "Ian Whitney", "iwhitney@familyvoices.org", "https://familyvoices.org", "Family-centered care for children with special health needs runs straight through language access, which makes Family Voices a natural fit for a children's-hospital conference on this theme. Your perspective would resonate with the clinicians and advocates in the room. We'd be honored to have you partner with us."],

  // ───────────────────────────────────────────────────────────────────────
  // Chicago community, cultural, health, disability & publishing prospects.
  // Each note is individually written from what this org actually does — no
  // shared template. Contact titles are stripped to the name so the greeting
  // reads naturally; AMN (above) is our one official partner.
  // ───────────────────────────────────────────────────────────────────────
  ["Albert Whitman & Company", "John Quattrocchi", "mail@albertwhitman.com", "https://www.albertwhitman.com", "For nearly a hundred years your Park Ridge house has published the kind of children's books that let a kid finally recognize themselves on the page, across differences of language, ability, and background. That instinct, that every child deserves to be met in their own words, is the one this conference is built on. Our attendees are the interpreters, clinicians, and families who would treasure your titles, and an exhibitor table would put them right in their hands."],
  ["AMA Foundation", "", "amafoundation@ama-assn.org", "https://www.ama-assn.org", "The AMA Foundation's work on health literacy runs straight into the question at the center of this conference: when a family can't fully understand their child's care, what does it take to close that gap? You have spent years on that problem from the literacy side, and we would value the Foundation's voice alongside the interpreters and clinicians working it from the language side. We would be glad to explore having you partner with us."],
  ["American Indian Center of Chicago", "", "info@chicagoaic.org", "https://www.chicagoaic.org", "There is a part of the language-access conversation that too often gets left out, and it is the one the American Indian Center has held for decades: Indigenous languages and the people keeping them alive. A conference on true language access, in a city built on so many of those communities, is not complete without that perspective in the room. We would be honored to have the Center join us as a community partner."],
  ["Anixter Center", "Samantha Handley", "AskAnixter@anixter.org", "https://www.anixter.org", "Anixter Center sits at an intersection this conference takes seriously: people who are Deaf, disabled, or otherwise up against a communication barrier every day. True language access has to mean them too, not only spoken-language interpreting, and your work is a daily argument for that broader definition. We would be glad to have Anixter exhibit or partner with us and bring that lens to the floor."],
  ["Apna Ghar", "Neha Gill", "info@apnaghar.org", "https://www.apnaghar.org", "Apna Ghar means our home, and for immigrant survivors trying to find safety in an unfamiliar language, that is precisely what your work offers. The families you walk beside are the same ones our clinicians and interpreters are reaching, often at the hardest moments of their lives. We would love to have Apna Ghar join us as a community partner and keep the room grounded in that reality."],
  ["Asian American Chamber of Commerce of Illinois", "Megan Nakano", "info@aaccil.org", "https://www.aaccil.org", "Your Chamber is where Asian American businesses and families across Illinois find one another, and language runs through all of it, from how a family finds care to how a business serves its community. A children's-hospital conference on language access has a great deal to learn from that vantage point, and plenty to offer your members in return. We would be glad to have the Chamber join us as a community partner."],
  ["Asian Health Coalition", "Dr. Fornessa T. Randal", "info@asianhealth.org", "https://www.asianhealth.org", "Closing health gaps for Chicago's immigrant and limited-English families is not adjacent to this conference's mission; it is the mission. The Asian Health Coalition has been doing that work on the ground for years, and the clinicians, interpreters, and advocates who fill our room are your natural collaborators. We would be honored to have the Coalition partner with us."],
  ["Asian Human Services (Trellus)", "", "info@ahschicago.org", "https://www.ahschicago.org", "Asian Human Services is a rare thing, an immigrant-serving nonprofit and a community health center under one roof, which means you live the language-and-care intersection this conference is built around rather than studying it from a distance. The families who come through your doors are exactly the ones our attendees serve. We would be glad to have you partner with us and bring that dual perspective to the table."],
  ["ASPIRA Association", "", "info@aspira.org", "https://www.aspira.org", "ASPIRA has spent decades proving something this conference believes deeply: a young person developed in both of their languages, never asked to leave one at the door, goes further. That bilingual, youth-first conviction belongs in a conversation about reaching every child in the language they think and dream in. We would love to have ASPIRA join us as a partner."],
  ["Aspire", "Maggie Hassler", "mhassler@aspirechicago.com", "https://www.aspirechicago.com", "Aspire's therapists spend their days helping Chicago-area children with developmental disabilities find their words and their footing, which is true language access in one of its most tender forms. The clinicians and families in our room know exactly how hard-won that progress is. We would be glad to have Aspire with us, whether on the exhibitor floor or as a partner."],
];

// Tab-delimited (TSV) with a header row, so buildSponsorInviteRows maps columns
// by name and notes containing commas are not split.
export const PROSPECT_TARGETS_TSV =
  ["Company", "Contact", "Email", "Website", "Note"].join("\t") +
  "\n" +
  TARGETS.map((r) => r.join("\t")).join("\n");
