// Hand-curated starter prospect list for the bulk sponsor/exhibitor inviter.
// These are web-verified, fresh targets with a real published contact email.
// Intentionally LEFT OUT: already-confirmed sponsors (e.g. LanguageLine, paid)
// and orgs tied to confirmed speakers (Equiti/Alonzo, Tica/Will, NCIHC/Speroff),
// which are warm relationships to handle personally, not cold invites.
//
// The note is the per-org body of the invitation email: a genuinely tailored
// few sentences about why THIS org fits a children's-hospital language-access
// conference. It is the bulk of the email, not a single line. Edit freely.
// Tab-delimited so commas inside notes stay safe.

type Target = [company: string, contact: string, email: string, website: string, note: string];

const TARGETS: Target[] = [
  ["CyraCom", "", "getstarted@cyracom.com", "https://www.cyracom.com", "CyraCom's healthcare interpreting is already in the hospitals our attendees staff every day, so the exhibitor floor puts you face to face with the interpreters, language-services managers, and clinicians who actually use it. Hosted by a children's hospital, this conference gathers the pediatric and family-care teams who feel language barriers most acutely. We'd be glad to have CyraCom in the room."],
  ["AMN Healthcare Language Services", "", "lscs@amnhealthcare.com", "https://www.amnhealthcare.com/language-services/", "As an official AALB partner, AMN already stands with us, so this is less an introduction than an invitation to be in the room as the partner you are. Your video interpreting is a daily lifeline for the medical interpreters and hospital leaders this conference convenes, and a children's-hospital setting brings the pediatric teams and families where getting language right matters most. We'd love to have AMN exhibit and be recognized alongside us."],
  ["Propio Language Services", "Lisa Stokesbury", "lstokesbury@propio.com", "https://propio.com", "Propio has become one of the largest forces in healthcare interpreting, and our attendees are exactly the interpreters, agencies, and hospital buyers your growth depends on. As a children's-hospital conference on language access, we convene the people shaping how care reaches limited-English families. We'd be glad to have Propio exhibit and help set the tone for what comes next."],
  ["MasterWord Services", "", "info@masterword.com", "https://www.masterword.com", "MasterWord's training and language services are exactly what the interpreters and hospital partners at this conference come to find, and your work in healthcare is well known to this community. Hosted by a children's hospital, we draw the pediatric and family-care teams who live language access every day. We'd love to have MasterWord exhibit with us."],
  ["Wordly", "", "contact@wordly.ai", "https://www.wordly.ai", "Wordly sits right at the 'Tomorrow' in our theme, and there's a real opportunity on two fronts: an exhibitor presence in front of a national healthcare-interpreting audience, and powering live translation for the conference itself. As a children's-hospital event, we're focused on reaching every family in their own language. We'd love to explore both with you."],
  ["Jeenie", "", "support@jeenie.com", "https://jeenie.com", "Jeenie's on-demand model speaks straight to the 'Tomorrow' side of our theme, and the interpreters and hospital teams at this conference are exactly the community you're building for. Hosted by a children's hospital, we gather the pediatric and family-care professionals who feel language gaps first. We'd be glad to have Jeenie exhibit and meet them."],
  ["Gallaudet University", "", "sponsorship@gallaudet.edu", "https://gallaudet.edu", "Deaf and ASL access is core to true language access, and Gallaudet's presence would mean a great deal to the interpreters, clinicians, and advocates at this conference. As a children's-hospital event, we're thinking about Deaf children and families as much as spoken-language ones. We'd love to have Gallaudet exhibit and introduce your programs to a national audience."],
  ["CCHI", "", "admin@cchicertification.org", "https://cchicertification.org", "So many of our attendees hold CCHI certification that the conference is essentially your community in one room: the healthcare interpreters and trainers who built their careers on your credential. Hosted by a children's hospital, it centers the pediatric and family-care settings where certified interpreting matters most. We'd love to have CCHI exhibit and connect with them directly."],
  ["IMIA", "", "outreach@imiaweb.org", "https://www.imiaweb.org", "IMIA's membership and our attendees are largely the same people, the medical interpreters working at the front lines of language access, so an exhibitor table puts you face to face with your community. As a children's-hospital conference, we draw the pediatric teams and families who depend on skilled interpreting. We'd be glad to have IMIA join us."],
  ["American Translators Association", "Chelsey Sleeter", "sponsorship@atanet.org", "https://www.atanet.org", "The ATA's healthcare-interpreting community overlaps heavily with our attendees, and your structured sponsor program tells us you value being in rooms like this. Hosted by a children's hospital, we gather the pediatric and family-care interpreters and clinicians at the center of language access. We'd love to have the ATA exhibit with us."],
  ["Registry of Interpreters for the Deaf", "", "communications@rid.org", "https://rid.org", "For the Deaf-access side of this conference, RID's presence would be invaluable, since your members are the ASL interpreters our attendees work alongside every day. As a children's-hospital event, we're focused on Deaf children and families as much as anyone. We'd love to have RID join us on the floor."],
  ["Tarjimly", "", "yassin@tarjim.ly", "https://www.tarjimly.org", "Tarjimly's work connecting refugees and immigrants with interpreters is the very heart of what this conference is about. Hosted by a children's hospital, we see how language access changes outcomes for immigrant and refugee families and their children. We'd love to have Tarjimly exhibit and share your mission with this audience."],

  // Pediatric / children's angle (this is a children's-hospital conference).
  // Web-verified contacts only; the big children's brands (Abbott, Enfamil,
  // Medela, WTTW, Ronald McDonald House) are relationship/form-only and live
  // in the separate creative-targets file for manual outreach, not here.
  ["American Academy of Pediatrics", "", "ksamp@aap.org", "https://www.aap.org", "As the home of American pediatrics, and practically our neighbor in Itasca, the AAP belongs at a children's-hospital conference on language access. Your own policy work on immigrant child health and language services speaks directly to our theme. We'd be honored to have the AAP exhibit or partner with us."],
  ["Sesame Workshop", "", "Partnerships@sesame.org", "https://sesameworkshop.org", "Few organizations have done more for immigrant and refugee children in their own languages than Sesame Workshop, and that mission is the spirit of this conference. Hosted by a children's hospital, we gather the clinicians, interpreters, and advocates serving exactly those families. We'd love to explore having Sesame Workshop join us as a partner."],
  ["Reach Out and Read", "", "info@reachoutandread.org", "https://reachoutandread.org", "Reach Out and Read already lives where this conference does, inside the pediatric visit, putting books into families' hands in dozens of languages. As a children's-hospital event on language access, the fit is genuine and meaningful. We'd love to have you in the room and to explore a partnership."],
  ["Lee & Low Books", "", "sales@leeandlow.com", "https://www.leeandlow.com", "As the leading publisher of bilingual and multicultural children's books, Lee & Low would be a natural and welcome presence at a children's-hospital conference on language access. Our attendees, who serve multilingual families every day, would truly value your titles. We'd love to have you exhibit with us."],
  ["Children's Hospital Association", "", "memberservices@childrenshospitals.org", "https://www.childrenshospitals.org", "Lurie Children's is one of your members, and language access is a shared priority across every children's hospital the CHA represents. This conference convenes the pediatric language-access community your members rely on. We'd be glad to have the CHA partner with us and reach that audience."],
  ["La Rabida Children's Hospital", "Anne Mullen", "amullen@larabida.org", "https://larabida.org", "As a fellow Chicago children's hospital serving so many Medicaid and multilingual families, La Rabida is a natural ally for this conference. The families you care for are exactly who our work is about. We'd love to have La Rabida exhibit or join us as a community partner."],
  ["Family Voices", "Ian Whitney", "iwhitney@familyvoices.org", "https://familyvoices.org", "Family-centered care for children with special health needs runs straight through language access, which makes Family Voices a natural fit for a children's-hospital conference on this theme. Your perspective would resonate with the clinicians and advocates in the room. We'd be honored to have you partner with us."],

  // ───────────────────────────────────────────────────────────────────────
  // Chicago community, cultural, health, disability & publishing prospects.
  // Each note is individually written from what this org actually does — no
  // shared template. Contact titles are stripped to the name so the greeting
  // reads naturally; AMN (above) is our one official partner.
  // ───────────────────────────────────────────────────────────────────────
  ["Albert Whitman & Company", "John Quattrocchi", "mail@albertwhitman.com", "https://www.albertwhitman.com", "For nearly a hundred years your Park Ridge house has published the kind of children's books that let a kid finally recognize themselves on the page, across differences of language, ability, and background. That instinct, that every child deserves to be met in their own words, is the one this conference is built on. Our attendees are the interpreters, clinicians, and families who would treasure your titles, and an exhibitor table would put them right in their hands."],
  ["AMA Foundation", "", "amafoundation@ama-assn.org", "https://www.ama-assn.org", "The AMA Foundation's work on health literacy runs straight into the question at the center of this conference: when a family can't fully understand their child's care, what does it take to close that gap? You work that problem from the literacy side, and we would value the Foundation's voice alongside the interpreters and clinicians working it from the language side. We would be glad to explore having you partner with us."],
  ["American Indian Center of Chicago", "", "info@chicagoaic.org", "https://www.chicagoaic.org", "There is a part of the language-access conversation that too often gets left out, and it is the one the American Indian Center has long held: Indigenous languages and the people keeping them alive in Chicago. A conference on true language access is not complete without that perspective in the room. We would be honored to have the Center join us as a community partner."],
  ["Anixter Center", "Samantha Handley", "AskAnixter@anixter.org", "https://www.anixter.org", "Anixter Center sits at an intersection this conference takes seriously: people who are Deaf, disabled, or otherwise up against a communication barrier every day. True language access has to mean them too, not only spoken-language interpreting, and your work is a daily argument for that broader definition. We would be glad to have Anixter exhibit or partner with us and bring that lens to the floor."],
  ["Apna Ghar", "Neha Gill", "info@apnaghar.org", "https://www.apnaghar.org", "Apna Ghar's work supporting immigrant survivors and families across language and culture sits at the heart of this conference. The families you walk beside are the same ones our clinicians and interpreters are reaching, often at the hardest moments of their lives. We would love to have Apna Ghar join us as a community partner and keep the room grounded in that reality."],
  ["Asian American Chamber of Commerce of Illinois", "Megan Nakano", "info@aaccil.org", "https://www.aaccil.org", "Your Chamber is where Asian American businesses and families across Illinois find one another, and language runs through all of it, from how a family finds care to how a business serves its community. A children's-hospital conference on language access has a great deal to learn from that vantage point, and plenty to offer your members in return. We would be glad to have the Chamber join us as a community partner."],
  ["Asian Health Coalition", "Dr. Fornessa T. Randal", "info@asianhealth.org", "https://www.asianhealth.org", "Closing health gaps for Chicago's immigrant and limited-English families is not adjacent to this conference's mission; it is the mission. The Asian Health Coalition does exactly that work on the ground, and the clinicians, interpreters, and advocates who fill our room are your natural collaborators. We would be honored to have the Coalition partner with us."],
  ["Asian Human Services (Trellus)", "", "info@ahschicago.org", "https://www.ahschicago.org", "Asian Human Services is a rare thing, an immigrant-serving nonprofit and a community health center under one roof, which means you live the language-and-care intersection this conference is built around rather than studying it from a distance. The families who come through your doors are exactly the ones our attendees serve. We would be glad to have you partner with us and bring that dual perspective to the table."],
  ["ASPIRA Association", "", "info@aspira.org", "https://www.aspira.org", "ASPIRA's work developing Latino youth through education and bilingual leadership connects naturally to a conversation about reaching every child in the language they think and dream in. The families and communities you build up are the same ones our attendees serve. We would love to have ASPIRA join us as a partner."],
  ["Aspire", "Maggie Hassler", "mhassler@aspirechicago.com", "https://www.aspirechicago.com", "Aspire's therapists spend their days helping Chicago-area children with developmental disabilities find their words and their footing, which is true language access in one of its most tender forms. The clinicians and families in our room know exactly how hard-won that progress is. We would be glad to have Aspire with us, whether on the exhibitor floor or as a partner."],
  ["Ava", "", "advocacy@ava.me", "https://www.ava.me", "Ava puts live captions on a conversation the moment it happens, so a Deaf or hard-of-hearing person is never a beat behind the room. That is access measured in seconds, and it is exactly the standard this conference holds itself to. We'd love to have Ava on the exhibitor floor showing our attendees what real-time inclusion looks like."],
  ["Avenues to Independence", "Bob McNamara", "cragg@avenuestoindependence.org", "https://www.avenuestoindependence.org", "Avenues helps Chicago-area adults with autism, cerebral palsy, and other disabilities live and work with dignity, and dignity, in practice, begins with being understood. That conviction is the thread running through this entire conference. We'd be glad to have Avenues with us in the room."],
  ["Balzekas Museum of Lithuanian Culture", "Sigita Balzekas", "info@balzekasmuseum.org", "https://www.balzekasmuseum.org", "Your museum has kept the Lithuanian language and story alive for one of Chicago's largest immigrant communities, a quiet, ongoing act of language preservation. That long memory is something a conference on true language access wants in the room. We'd be glad to have the Balzekas Museum exhibit with us."],
  ["Cambodian Association of Illinois", "Chenda Taing", "contactus@cambodian-association.org", "https://www.cambodian-association.org", "For refugee families rebuilding far from home, the Cambodian Association has been a place where language and culture are held onto rather than lost. The children of those families are precisely who our attendees care for. We'd be glad to have the Association join us as a community partner."],
  ["Casa Italia", "Peter Volpe", "info@casaitaliachicago.org", "https://www.casaitaliachicago.org", "Casa Italia has long been the gathering place for Chicagoland's Italian-American community and the heritage it carries. A conference about language and belonging is richer with that kind of cultural anchor present. We'd be glad to welcome Casa Italia to join us."],
  ["Center for Independent Futures", "Richard Malone", "center@independentfutures.com", "https://www.independentfutures.com", "Center for Independent Futures helps people with disabilities in the Chicago area build full, self-directed lives, and being able to communicate and be understood is where that independence begins. That is the heart of what we're convening around. We'd be glad to have you with us."],
  ["Centro Romero", "Daysi J. Funes", "receptionist@centroromero.org", "https://www.centroromero.org", "On the Northeast Side, Centro Romero has spent years opening doors for immigrant and refugee families, and language is the hinge every one of those doors turns on. The families you serve and the children our attendees treat are the same community. We'd love to have Centro Romero join us as a community partner."],
  ["Chicago Chinatown Chamber of Commerce", "Susan Ng-Harroun", "info@chicagochinatown.org", "https://www.chicagochinatown.org", "Your Chamber ties together the businesses and families of Chicago's Chinatown, a community whose connection to health and services runs through language at every step. That neighborhood-level knowledge is something this conference would genuinely learn from. We'd be glad to have the Chamber join us as a community partner."],
  ["Chicago Hearing Society (Anixter Center)", "Karen Graller Aguilar", "KAguilar@anixter.org", "https://www.chicagohearingsociety.org", "Deaf and hard-of-hearing access is core to what 'true language access' means here, and the Chicago Hearing Society's work with the local Deaf community would mean a great deal to our attendees. As a children's-hospital event, we think about Deaf children and families as much as spoken-language ones. We'd love to have the Society exhibit and introduce your services to a national audience."],
  ["Chinese American Museum of Chicago", "Caroline Ng", "visit@camochicago.org", "https://www.camochicago.org", "Your museum keeps Chinese American history and language present in the heart of the city, honoring roots that so many of the families our attendees serve still carry. A conference on language access is better for that perspective. We'd be glad to have the Museum join us as a community partner."],
  ["Chinese American Service League (CASL)", "Paul Luu", "donate@casl.org", "https://www.casl.org", "For decades CASL has been a lifeline for Chicago's Chinese American families, bridging language and culture across health, aging, and child services. That mission sits at the center of this children's-hospital conference on language access. We'd be glad to have CASL partner with us and connect with this audience."],
  ["Chinese Mutual Aid Association", "Rhea Yap", "info@chinesemutualaid.org", "https://www.chinesemutualaid.org", "Chinese Mutual Aid Association helps immigrant and refugee families in Chicago find their footing, and language access is the groundwork beneath that stability. The families you steady are the ones our clinicians meet in the exam room. We'd love to have you join us and share your work."],
  ["Clearbrook", "", "info@clearbrook.org", "https://www.clearbrook.org", "Clearbrook's early-intervention and disability services help young children communicate and grow from their earliest days, when supporting a child's communication can shape everything that follows. That is language access at its most foundational. We'd be glad to have Clearbrook exhibit or partner with us."],
  ["Coalition of Limited English Speaking Elderly (CLESE)", "Marta Pereyra", "marta@clese.org", "https://www.clese.org", "Few organizations are as squarely on this conference's theme as CLESE: serving limited-English-speaking elders is language access in its most distilled form. The interpreters, clinicians, and advocates in our room share that calling. We'd be honored to have CLESE partner with us."],
  ["CommunityHealth", "Stephanie D. Willding", "info@communityhealth.org", "https://www.communityhealth.org", "As one of the nation's largest free clinics, CommunityHealth meets uninsured and immigrant patients across Chicago where they are, which makes language access a daily, practical necessity rather than an ideal. That lived expertise is exactly what our attendees come to trade. We'd be glad to have CommunityHealth partner with us."],
  ["DuSable Black History Museum and Education Center", "Perri Irmer", "info@dusablemuseum.org", "https://www.dusablemuseum.org", "The DuSable's education work reaches Chicago's Black and immigrant communities, a reminder that language access lives inside a larger story about who gets heard. We'd value that vantage point at a conference rooted in pediatric care. We'd love to have the DuSable with us."],
  ["Easterseals (National HQ)", "", "info@easterseals.com", "https://www.easterseals.com", "Easterseals has long championed children and families with disabilities, and communication access is inseparable from the language access this conference is built on. Many of the families you serve are ours too. We'd be glad to have Easterseals exhibit or partner with us."],
  ["Easterseals DuPage & Fox Valley", "", "info@eastersealsdfvr.org", "https://www.eastersealsdfvr.org", "Your pediatric therapists and AAC specialists help children find their voice, sometimes literally, which is communication access at its most hands-on. The clinicians and parents in our room live that work. We'd love to have Easterseals DuPage & Fox Valley on the exhibitor floor."],
  ["El Valor", "Rey B. Gonzalez", "info@elvalor.net", "https://www.elvalor.net", "Rooted in Chicago's Latino community, El Valor's bilingual work with children and adults with disabilities sits right at the crossroads this conference explores, where language access and disability access meet. The families you serve are the families our attendees treat. We'd be glad to have El Valor exhibit or partner with us."],
  ["Envision Unlimited", "Mark McHugh", "info@envisionunlimited.org", "https://www.envisionunlimited.org", "Envision serves Chicagoans with disabilities from infancy through adulthood, and for many of them communication support is what makes being understood possible at all. That is the question this conference exists to answer. We'd welcome Envision in the room."],
  ["Erie Family Health Centers", "", "info@eriefamilyhealth.org", "https://www.eriefamilyhealth.org", "At Erie, caring for Chicago's immigrant and multilingual families is a daily practice rather than an abstraction, which is exactly why your teams know things our attendees come to learn. As a children's-hospital conference on language access, we convene the clinicians and language-services staff you already work beside. We'd be glad to have Erie partner with us."],
  ["Erie Neighborhood House", "", "media@eriehouse.org", "https://www.eriehouse.org", "Erie Neighborhood House has walked with Chicago's immigrant families for generations, and language access is woven into nearly every program you run. That continuity, knowing a community across decades, is rare and valuable. We'd be glad to have Erie Neighborhood House join us as a community partner."],
  ["Esperanza Community Services", "", "info@esperanzacommunity.org", "https://www.esperanzacommunity.org", "Esperanza's bilingual support for children and adults with developmental disabilities brings language access and disability access together in one place, the same intersection this conference sits on. The families you serve are ours too. We'd love to have Esperanza join us as a partner."],
  ["Ethiopian Community Association of Chicago", "", "info@ecachicago.org", "https://www.ecachicago.org", "Welcoming Ethiopian and East African families to Chicago, and helping them find their footing across language, health, and a new home, is the kind of work this conference exists to honor. The children in those families are exactly who our attendees serve. We'd be glad to have the Association join us as a partner."],
  ["Exodus World Service", "", "info@exodusworldservice.org", "https://www.exodusworldservice.org", "Exodus World Service welcomes refugee families to the Chicago area and walks beside them as they settle, a journey where language access opens every door. As a children's-hospital conference on this theme, we serve those same families and children. We'd be glad to have Exodus join us as a community partner."],
  ["Friend Health", "", "friendhealth@friendhealth.org", "https://www.friendfhc.org", "Across your South Side health centers, you care for patients in the language they understand best, every single day. That is the practice this conference is gathered to celebrate and strengthen. We'd love to have Friend Health in the room."],
  ["Giant Steps Illinois", "Dr. Sylvia Smith", "ssmith@mygiantsteps.org", "https://www.mygiantsteps.org", "Giant Steps helps children with autism find ways to communicate and learn, which is the very heart of what 'true language access' has to include. The clinicians and families in our room understand that work intimately. We'd love to have Giant Steps join us in Chicago."],
  ["Glenkirk", "Christeon Mayfield", "cmayfield@glenkirk.org", "https://www.glenkirk.org", "For half a century Glenkirk has stood with Chicago-area families touched by developmental disability, and making sure every person has a way to be understood is the center of that mission and of this conference. We'd welcome Glenkirk with us."],
  ["Global Interpreting Network", "", "sales@globalinterpreting.com", "https://www.globalinterpreting.com", "Your Chicago-based interpreters work alongside the very hospitals and clinicians this conference convenes, which makes the exhibitor floor a natural meeting place rather than a cold introduction. We bring together the pediatric and family-care teams who rely on skilled interpreting daily. We'd love to have Global Interpreting Network exhibit with us."],
  ["Haitian American Museum of Chicago", "Elsie Hector Hernandez", "info@hamoc.org", "https://www.hamoc.org", "Your museum preserves Haitian art, culture, and language for Chicago's Haitian Creole-speaking families, who are exactly the patients true language access is meant to reach. That cultural grounding belongs in this conversation. We'd be honored to have the Museum in the room."],
  ["HANA Center", "Danae Kovac", "info@hanacenter.org", "https://www.hanacenter.org", "HANA Center supports Korean American, immigrant, and multiethnic families across Chicago, with language access running through the center of it all. That mission and ours are close kin. We'd be glad to have HANA Center partner with us."],
  ["Hanul Family Alliance", "Noah Kim", "noahkim@hanulusa.org", "https://www.hanulusa.org", "Hanul Family Alliance serves Chicago's Korean American and immigrant families across health, aging, and family services, where language access makes the difference at each stage. The children in those families are who our attendees serve. We'd love to have Hanul join us and share your mission."],
  ["Heartland Alliance (RICS)", "", "rics@heartlandalliance.org", "https://www.heartlandalliance.org", "Heartland Alliance's refugee and immigrant services help families build entirely new lives in Chicago, and language access threads through every step of that rebuilding. The children of those families are our attendees' patients. We'd love to have Heartland Alliance join us as a partner."],
  ["Helping Hand Center", "Bill Dwyer", "info@hhcenter.org", "https://www.hhcenter.org", "Helping Hand helps Chicagoland children and adults with disabilities learn and communicate, which is precisely the access this conference is about. The clinicians and families in our room share that goal. We'd be glad to have Helping Hand join us."],
  ["Illinois Assistive Technology Program (IATP)", "", "iatp@iltech.org", "https://www.iltech.org", "IATP helps people with disabilities across Illinois find the tools that let them communicate and live independently, which is communication access at its most practical and statewide. As a children's-hospital conference on language access, we'd value your presence. We'd love to have IATP exhibit with us."],
  ["Illinois Chapter, American Academy of Pediatrics (ICAAP)", "Jennie Pinkwater", "jpinkwater@illinoisaap.com", "https://www.illinoisaap.org", "As the voice of Illinois' pediatricians, ICAAP shares this conference's belief that every child and family deserves to be understood in their own language. Your members are, quite literally, our audience. We'd be honored to have the Illinois Chapter join us and to welcome your members into the room."],
  ["Illinois Coalition for Immigrant & Refugee Rights (ICIRR)", "Dagmara Avelar", "davelar@icirr.org", "https://www.icirr.org", "ICIRR brings immigrant and refugee organizations across Illinois under one banner, giving voice to the very families this conference exists to serve. Having your coalition's perspective in the room would sharpen the whole conversation. We'd love to explore partnering with ICIRR and connecting with your network."],
  ["Illinois Primary Health Care Association (IPHCA)", "Ollie Idowu", "iphca@iphca.org", "https://www.iphca.org", "Illinois' community health centers care for the limited-English and immigrant families at the heart of this conference, and as their statewide champion, IPHCA carries a primary-care perspective on language access we'd genuinely value. We'd be glad to have IPHCA with us."],
  ["Illinois Public Health Association (IPHA)", "Tom Hughes", "thughes@ipha.com", "https://www.ipha.com", "Public health and language access are inseparable for the Illinois families IPHA serves, and your statewide voice would land with the clinicians and advocates in this room. The reach you bring is exactly the kind this conversation needs. We'd love to have IPHA with us."],
  ["Illinois Speech-Language-Hearing Association (ISHA)", "Paul Doggett", "executivedirector@ishail.org", "https://www.ishail.org", "Your members are the speech-language pathologists and audiologists who open up communication for children every day, which makes ISHA a near-perfect fit for a children's-hospital conference on true language access. The work your members do is the work our attendees gather around. We'd love to have ISHA exhibit and connect with this audience."],
  ["Indo-American Center", "", "info@indoamerican.org", "https://www.indoamerican.org", "The Indo-American Center helps immigrant families across Chicago navigate health, language, and a new home. The children in those families are exactly who our attendees serve. We'd be glad to have the Indo-American Center join us as a community partner."],
  ["Infant Welfare Society of Chicago", "", "info@infantwelfare.org", "https://www.infantwelfare.org", "For more than a century the Infant Welfare Society has cared for Chicago's children and families, with bilingual care meeting them where they are. That mission fits this children's-hospital conference on language access naturally. We'd be glad to have you exhibit or partner with us."],
  ["International Latino Cultural Center of Chicago", "Mateo Mulcahy", "info@latinoculturalcenter.org", "https://www.latinoculturalcenter.org", "Your center celebrates Latino arts and culture across Chicago, holding the language and heritage so many of the families our attendees serve carry with them. That cultural depth enriches a conversation about language access. We'd be glad to have the Center join us as a community partner."],
  ["Irish American Heritage Center", "", "info@irishahc.org", "https://www.irish-american.org", "Your center keeps Irish language and heritage alive in Chicago, one thread in the immigrant story this conference honors. A gathering about language access is fuller with that history present. We'd be glad to have the Irish American Heritage Center join us as a community partner."],
  ["Keshet", "", "admin@keshet.org", "https://www.keshet.org", "Keshet makes sure children and adults with disabilities are included and genuinely heard across Chicago, and that insistence on being heard is the spirit of this whole conference. The families you serve are ours too. We'd be glad to have Keshet with us."],
  ["Korean American Association of Chicago (KAAC)", "", "34kaac@koreachicago.org", "https://www.koreachicago.org", "KAAC has long been a hub for Chicago's Korean American community, a place where language shapes a family's connection to health and services. That community knowledge would resonate in our room. We'd love to have the Korean American Association join us as a community partner."],
  ["Lawndale Christian Health Center", "James Brooks", "info@lawndale.org", "https://www.lawndale.org", "Lawndale serves one of Chicago's most diverse communities, where meeting families in their own language is simply part of daily care. The clinicians and language-services teams you employ are exactly who this conference convenes. We'd love to have Lawndale partner with us."],
  ["Little Friends", "Jason Altenbern", "jaltenbern@lilfriends.com", "https://www.littlefriendsinc.org", "For decades Little Friends has helped Chicago-area children with autism communicate and thrive, which lands squarely on this conference's theme. The clinicians and families in our room recognize that work. We'd be glad to have Little Friends with us."],
  ["Mujeres Latinas en Accion", "Linda Tortolero", "mail@mujereslat.org", "https://www.mujereslatinasenaccion.org", "Mujeres Latinas en Accion has empowered Latina women and families in Chicago for decades, with language access woven through your health and family services. The mothers and children you support are who our attendees serve. We'd love to have you join us as a community partner."],
  ["Multilingual Connections", "", "contact@mlconnections.com", "https://www.mlconnections.com", "Your Evanston team has spent years helping organizations reach multilingual audiences with real nuance and care, which is the craft at the heart of this conference. We convene the interpreters, clinicians, and language-services teams who live that craft daily. We'd be glad to have Multilingual Connections exhibit with us."],
  ["Muslim Community Center (MCC)", "", "president@mccchicago.org", "https://www.mccchicago.org", "For more than fifty years the Muslim Community Center has anchored Chicago's Muslim immigrant community, families who deserve to be understood in their own language in every clinic they walk into. That is the standard this conference is working toward. We'd be honored to have you with us."],
  ["National Museum of Mexican Art", "", "info@nationalmuseumofmexicanart.org", "https://www.nationalmuseumofmexicanart.org", "Your museum is the beating heart of Mexican art, culture, and language in Chicago, and the Spanish-speaking families you celebrate are precisely the families this conference works to reach. That cultural pride belongs in the room. We'd love to have you with us."],
  ["Pan-African Association", "Elsa Woldegarima", "ewoldegarima@panafricanassociation.org", "https://www.panafricanassociation.org", "The Pan-African Association helps African refugee and immigrant families resettle and build thriving lives in Chicago, with language access central to that journey. The children of those families are who our attendees serve. We'd be glad to have you join us as a community partner."],
  ["Park Lawn", "Nancy Schmitz", "info@parklawn.com", "https://www.parklawn.com", "For decades Park Lawn has supported Chicago-area people with developmental disabilities, and making sure each person can be heard is the heart of both your work and this conference. We'd love to have Park Lawn join us."],
  ["Polish American Association", "", "paa@polish.org", "https://www.polish.org", "The Polish American Association has helped immigrant families across Chicago navigate language, health, and a new home for decades. The continuity of that work, and the children in those families, connect directly to what our attendees do. We'd be glad to have you join us as a community partner."],
  ["Puerto Rican Arts Alliance", "Ignacio Lopez", "info@praachicago.org", "https://www.praachicago.org", "The Puerto Rican Arts Alliance keeps culture and language alive for Chicago's Latino youth and families, a spirit that sits close to this conference's heart. That perspective would be welcome in the room. We'd be glad to have you join us as a community partner."],
  ["Ray Graham Association", "Mark Langan", "ProgramServices@RayGraham.org", "https://www.raygraham.org", "Ray Graham opens doors for people with disabilities across the Chicago suburbs, including the assistive technology that gives a person a voice, which is exactly what this conference is about. The clinicians and families in our room rely on that technology. We'd welcome Ray Graham in the room."],
  ["RefugeeOne", "Melineh Kano", "info@refugeeone.org", "https://www.refugeeone.org", "RefugeeOne helps newly arrived families rebuild their lives in Chicago, and language access runs through every chapter of that rebuilding, from the first clinic visit onward. The children in those families are exactly who our attendees serve. We'd love to have RefugeeOne join us and share your work with this community."],
  ["Search Inc", "", "info@search-inc.org", "https://www.search-inc.org", "For more than fifty years Search has helped Chicago-area people with disabilities live and be heard, which is the same outcome this conference is chasing. The clinicians and families in our room would recognize your work immediately. We'd love to have Search with us."],
  ["Segundo Ruiz Belvis Cultural Center", "Omar Torres-Kortright", "info@srbcc.org", "https://www.srbcc.org", "Your center keeps Puerto Rican and Latino culture and language thriving in Chicago, part of the broader language access this conference is built to celebrate. That cultural grounding would be welcome in the room. We'd love to have the Segundo Ruiz Belvis Cultural Center join us as a community partner."],
  ["Shore Community Services", "Alexis Alm", "info@shoreservices.org", "https://www.shoreservices.org", "Shore's work improving life for Chicago-area people with intellectual and developmental disabilities turns on a simple thing: making sure everyone can communicate and be heard. That is the heart of this conference. We'd love to have Shore join us."],
  ["Sound World Solutions", "", "press@soundworldsolutions.com", "https://www.soundworldsolutions.com", "Your affordable hearing technology makes communication possible for people who might otherwise go without, which is access in the truest sense of the word. As a conference that centers Deaf and hard-of-hearing families, we'd value that on the floor. We'd love to have Sound World Solutions exhibit with us."],
  ["Swedish American Museum", "Karin Moen Abercrombie", "kabercrombie@samac.org", "https://www.swedishamericanmuseum.org", "Your museum tells the immigrant story through a Swedish American lens, a reminder of how language and heritage shape every family's path into a new country. That perspective belongs at a conference about language access. We'd love to have the Swedish American Museum join us as a community partner."],
  ["Trinity Services", "Sherry Ladislas", "sladislas@trinityservices.org", "https://www.trinityservices.org", "Trinity helps people with disabilities flourish, and communication, being able to express and be understood, is inseparable from that flourishing. That belief sits at the center of this conference. We'd be glad to have Trinity with us in Chicago."],
  ["Turning Pointe Autism Foundation", "Barb Brauer", "contactus@turningpointeaf.org", "https://www.turningpointeautismfoundation.org", "Your day school and therapies help children with autism find their voice, which is the very definition of true language access. The clinicians and families in our room do that work alongside you. We'd love to have Turning Pointe join us."],
  ["UCP Seguin - Infinitec", "", "infinitecwebsupport@ucpnet.org", "https://www.ucpseguin.org", "Infinitec's work putting assistive technology into the hands of children with disabilities connects straight to a conference about reaching every child, in every language and every mode of communication. Our attendees rely on exactly that technology. We'd love to have you exhibit with us."],
  ["Ukrainian National Museum of Chicago", "Zachary Dmyterko", "info@ukrainiannationalmuseum.org", "https://www.ukrainiannationalmuseum.org", "Your museum serves Chicago's Ukrainian immigrant and refugee families, for whom language access is not a topic but daily life. That lived reality belongs in this room. We'd be honored to have you with us."],
  ["Vietnamese Association of Illinois", "Van Huynh", "infovai@hnvi.org", "https://www.vietnamese.org", "For decades the Vietnamese Association of Illinois has supported refugee and immigrant families across Chicago, where language shapes a family's connection to health and home. The children in those families are who our attendees serve. We'd love to have you join us as a community partner."],
  ["AbleNet", "", "customerservice@ablenetinc.com", "https://www.ablenetinc.com", "AbleNet's assistive and AAC technology helps children with disabilities communicate and learn, work that sits close to this conference's center. The clinicians and families in our room put your tools to use every day. We'd love to have AbleNet exhibit with us."],
  ["Accent on Languages", "", "info@accentonlanguages.com", "https://www.accentonlanguages.com", "Accent on Languages' interpreting and translation help providers connect with limited-English families, which is the daily work at the heart of this conference. The hospital teams and language-services staff you serve are exactly our audience. We'd be glad to have Accent on Languages exhibit with us."],
  ["Advanced Bionics", "", "hear@AdvancedBionics.com", "https://www.advancedbionics.com", "Advanced Bionics' cochlear implant technology helps Deaf children hear and connect with their families, which is access at its most profound. The clinicians and families in our room live on the other end of that technology. We'd love to have Advanced Bionics exhibit with us."],
  ["Affordable Language Services", "", "sales@affordablelanguages.com", "https://www.affordablelanguages.com", "Affordable Language Services' interpreting helps healthcare providers reach limited-English patients, the everyday practice this conference is built around. The clinicians and language-services teams you support fill our room. We'd love to have you exhibit with us."],
  ["American Society for Deaf Children", "Katie Chubb", "ed@deafchildren.org", "https://www.deafchildren.org", "The American Society for Deaf Children stands with families raising Deaf and hard-of-hearing kids, which is the very center of what this conference holds. We think about Deaf children and families as much as spoken-language ones, throughout. We'd be honored to have you exhibit or partner with us."],
  ["Arte Publico Press / Pinata Books", "", "bkorders@uh.edu", "https://artepublicopress.com", "As the nation's leading publisher of U.S. Hispanic literature, Arte Publico and Pinata Books help Latino children see themselves in stories, in both of their languages. Our attendees, who serve multilingual families every day, would genuinely value your titles. We'd be glad to have you exhibit with us."],
  ["AssistiveWare", "", "support@assistiveware.com", "https://www.assistiveware.com", "AssistiveWare's AAC apps give children who cannot speak a voice, including across languages, which fits this conference's theme beautifully. The clinicians and families in our room rely on tools like yours. We'd be glad to have AssistiveWare exhibit with us."],
  ["Attainment Company", "", "info@attainmentcompany.com", "https://www.attainmentcompany.com", "Attainment Company's AAC and learning tools help children communicate and build independence, which lands right on a conference about reaching every child. Our attendees put those tools to work daily. We'd love to have Attainment Company exhibit with us."],
  ["Avaz AAC", "", "collaborate@avazapp.com", "https://www.avazapp.com", "Avaz's multilingual AAC apps let children communicate in their own language, which is the exact spirit of this conference distilled into software. The clinicians and families in our room use AAC every day. We'd love to have Avaz exhibit with us."],
  ["Bobbie", "", "hello@hibobbie.com", "https://www.hibobbie.com", "Bobbie's work on infant nutrition and feeding equity speaks to a children's-hospital conference focused on reaching every family, including at the very start of a child's life. Our attendees care for the youngest patients and their parents daily. We'd love to explore having Bobbie join us."],
  ["Center for Hearing and Communication", "Nancy Nadler", "info@chchearing.org", "https://www.chchearing.org", "Your work helping people who are Deaf or hard of hearing communicate fully connects straight to a conference that centers those families. As a children's-hospital event, we serve Deaf and HoH children and their parents. We'd be glad to have the Center for Hearing and Communication exhibit with us."],
  ["Charlesbridge Publishing", "", "trademarketing@charlesbridge.com", "https://www.charlesbridge.com", "Charlesbridge's diverse and bilingual children's titles help kids meet the world across language and culture, exactly the books our attendees would want in a child's hands. As a children's-hospital conference on language access, the fit is genuine. We'd love to have Charlesbridge exhibit with us."],
  ["Day Translations", "", "contact@daytranslations.com", "https://www.daytranslations.com", "Day Translations' interpreting and translation work helps organizations connect across languages, the daily reality for the healthcare teams in our room. We gather the interpreters and language-services staff who share that work. We'd be glad to have Day Translations exhibit with us."],
  ["Dynamic Language", "", "inbound@dynamiclanguage.com", "https://www.dynamiclanguage.com", "Dynamic Language's interpreting and translation services support healthcare teams reaching limited-English families, which sits at the center of this conference. We convene exactly that community of clinicians and language-services teams. We'd love to have Dynamic Language exhibit with us."],
  ["Enabling Devices", "", "sales@enablingdevices.com", "https://www.enablingdevices.com", "Enabling Devices' adapted and AAC tools help children with disabilities communicate and play, work that sits close to this conference's heart. The clinicians and families in our room rely on tools like yours. We'd be glad to have Enabling Devices exhibit with us."],
  ["Eriksen Translations", "", "info@eriksen.com", "https://www.eriksen.com", "Eriksen's translation and interpreting help organizations reach multilingual communities with care, which our attendees value deeply. We gather the language-services teams and clinicians who share that mission. We'd be glad to have Eriksen exhibit with us."],
  ["Forbes AAC", "", "sales@forbesaac.com", "https://www.forbesaac.com", "Forbes AAC's speech-generating devices give children a voice, which is communication access in its truest form. The clinicians and families in our room rely on that technology. We'd be glad to have Forbes AAC exhibit with us."],
  ["Hands & Voices", "", "parentadvocate@handsandvoices.org", "https://www.handsandvoices.org", "Hands & Voices supports families of Deaf and hard-of-hearing children without pushing any one communication choice, which is, in a word, what true language access means. We center exactly those families. We'd be honored to have Hands & Voices join us as a partner."],
  ["Health Literacy Media", "", "info@healthliteracy.media", "https://www.healthliteracy.media", "Health Literacy Media's work making health information clear and reachable connects directly to a conference about helping every family understand their child's care. The clinicians and advocates in our room share that goal. We'd love to have you exhibit or partner with us."],
  ["Hearing Loss Association of America", "Nancy Macklin", "development@hearingloss.org", "https://www.hearingloss.org", "HLAA's work supporting people with hearing loss connects straight to a conference that centers Deaf and hard-of-hearing families. We serve children and families navigating hearing loss every day. We'd love to have HLAA exhibit with us."],
  ["Hispanic Federation", "", "info@hispanicfederation.org", "https://www.hispanicfederation.org", "The Hispanic Federation strengthens Latino communities across the country, where language access shapes a family's connection to health and opportunity. The children in those communities are who our attendees serve. We'd love to have the Hispanic Federation join us as a partner."],
  ["InnoCaption", "", "marketing@innocaption.com", "https://www.innocaption.com", "InnoCaption's real-time captioning keeps Deaf and hard-of-hearing people connected by phone, the kind of everyday access this conference champions. As an event centering Deaf and HoH families, your work speaks straight to our theme. We'd love to have InnoCaption exhibit with us."],
  ["John Tracy Center", "", "web@jtc.org", "https://www.jtc.org", "The John Tracy Center has guided families of young Deaf and hard-of-hearing children for generations, work that sits at the very center of this conference. We center exactly those families. We'd be glad to have you exhibit or partner with us."],
  ["Language Lizard", "", "info@languagelizard.com", "https://www.languagelizard.com", "Language Lizard's bilingual books and resources help children and families connect across dozens of languages, which is exactly the spirit of this conference. Our attendees serve multilingual families every day. We'd love to have Language Lizard exhibit with us."],
  ["Language Services Associates", "Nicole Wetten", "nwetten@lsa.inc", "https://www.lsaweb.com", "LSA's healthcare interpreting supports the hospitals and clinicians this conference convenes, which makes the exhibitor floor a natural fit rather than an introduction. We bring together the pediatric and family-care teams who rely on your services. We'd be glad to have LSA exhibit with us."],
  ["Lectura Books", "", "info@lecturabooks.com", "https://www.lecturabooks.com", "Lectura Books brings Latino families together around bilingual reading, which lands naturally at a children's-hospital conference on language access. Our attendees serve multilingual families every day. We'd be glad to have Lectura Books exhibit with us."],
  ["Lighthouse Translations", "", "translations@lighthouseonline.com", "https://www.lighthouseonline.com", "Lighthouse Translations' language services help organizations reach across languages, work the healthcare teams in our room know well. We convene the interpreters and language-services staff who share that mission. We'd love to have Lighthouse exhibit with us."],
  ["Lingraphica", "", "events@lingraphica.com", "https://www.lingraphica.com", "Lingraphica's communication devices and therapy support help people regain and find their voice, work that connects to the heart of this conference. The clinicians and families in our room rely on AAC daily. We'd be glad to have Lingraphica exhibit with us."],
  ["LinguaLinx", "Jacob Pickard", "jpickard@lingualinx.com", "https://www.lingualinx.com", "LinguaLinx's language services help organizations reach multilingual communities, work the healthcare teams in our room know well. We convene the interpreters and language-services staff who share that mission. We'd love to have LinguaLinx exhibit with us."],
  ["Linguava Interpreters", "David Brackett", "david@linguava.com", "https://www.linguava.com", "Linguava's healthcare interpreting helps clinics and hospitals reach limited-English families, which is the daily work at the center of this conference. We convene exactly the clinicians and language-services teams you serve. We'd love to have Linguava exhibit with us."],
  ["LoganTech (Logan ProxTalker)", "", "info@logantech.com", "https://www.logantech.com", "LoganTech's tactile AAC devices give children a hands-on way to communicate, which is communication access made tangible. The clinicians and families in our room rely on AAC daily. We'd be glad to have LoganTech exhibit with us."],
  ["MALDEF", "", "info@maldef.org", "https://www.maldef.org", "MALDEF's advocacy for Latino civil rights, language access very much included, connects directly to the families this conference exists to serve. The clinicians and advocates in our room share that commitment. We'd love to have MALDEF join us as a partner."],
  ["MED-EL", "", "customerservice.us@medel.com", "https://www.medel.com", "MED-EL's hearing implants open the world of sound and language to Deaf children, which is the heart of what this conference is about. The clinicians and families in our room depend on your technology. We'd be glad to have MED-EL exhibit with us."],
  ["National Association of the Deaf", "", "nad.info@nad.org", "https://www.nad.org", "As the nation's leading voice for the Deaf community, the NAD's presence would mean a great deal to the interpreters, clinicians, and advocates in this room. As a children's-hospital event, we center Deaf children and families throughout. We'd love to have the NAD exhibit and join us on the floor."],
  ["Nemours KidsHealth", "", "Partnership@KidsHealth.org", "https://www.kidshealth.org", "KidsHealth's multilingual health information helps families understand their children's care in their own language, which is this conference's theme stated plainly. The clinicians and families in our room use your resources. We'd love to have Nemours KidsHealth exhibit or partner with us."],
  ["Otsimo", "", "support@otsimo.com", "https://www.otsimo.com", "Otsimo's special-education and AAC apps help children with disabilities learn and communicate, work that fits a conference about reaching every child. The clinicians and families in our room use tools like yours. We'd be glad to have Otsimo exhibit with us."],
  ["PRC-Saltillo", "", "info@prc-saltillo.com", "https://www.prc-saltillo.com", "PRC-Saltillo's communication devices help children find their voice, including in more than one language, which fits this conference's theme exactly. The clinicians and families in our room rely on your technology. We'd love to have PRC-Saltillo exhibit with us."],
  ["Serene Innovations", "", "cs@sereneinnovations.com", "https://www.sereneinnovations.com", "Serene Innovations' amplified and alerting devices help people who are hard of hearing stay connected and safe, access in a practical, daily sense. As a conference centering Deaf and HoH families, we'd value your presence. We'd be glad to have you exhibit with us."],
  ["Speak for Yourself", "", "info@speakforyourself.org", "https://www.speakforyourself.org", "Speak for Yourself's AAC app gives children who cannot speak a way to say what they actually mean, which is communication access at its core. The clinicians and families in our room rely on it. We'd be glad to have Speak for Yourself exhibit with us."],
  ["Star Bright Books", "", "info@starbrightbooks.com", "https://www.starbrightbooks.com", "Star Bright Books' multilingual children's titles help every child see themselves in a story, whatever language they speak at home. As a children's-hospital conference on language access, our attendees would truly value your books. We'd be glad to have Star Bright Books exhibit with us."],
  ["Talk To Me Technologies", "", "hello@smartboxaac.com", "https://www.talktometechnologies.com", "Talk To Me Technologies helps children who cannot speak communicate in their own words, which is the essence of communication access. The clinicians and families in our room rely on AAC daily. We'd be glad to have you exhibit with us."],
  ["Therapy Box (Predictable)", "", "support@therapy-box.co.uk", "https://www.therapy-box.co.uk", "Therapy Box's communication apps help people find their voice across abilities and languages, which fits this conference's theme well. The clinicians and families in our room use AAC every day. We'd love to have Therapy Box exhibit with us."],
  ["Tobii Dynavox", "", "css@tobiidynavox.com", "https://www.tobiidynavox.com", "Tobii Dynavox's AAC technology gives children who cannot speak a way to be heard, which is the very heart of communication access. The clinicians and families in our room rely on your devices. We'd be glad to have Tobii Dynavox exhibit with us."],
  ["UnidosUS", "", "info@unidosus.org", "https://www.unidosus.org", "As one of the nation's largest Latino advocacy organizations, UnidosUS speaks for the very families this conference exists to serve. The clinicians and advocates in our room work alongside your communities. We'd be honored to have UnidosUS join us as a partner."],
  ["Velazquez Press", "", "info@AcademicLearningCompany.com", "https://www.velazquezpress.com", "Velazquez Press's bilingual dictionaries and learning materials help Spanish-speaking children and families bridge two languages, which is the heart of this conference. Our attendees serve exactly those families. We'd love to have Velazquez Press exhibit with us."],
  ["Widgit Health", "", "info@widgit.com", "https://www.widgit-health.com", "Widgit's symbol-based and multilingual communication tools help hospitals reach patients across language and ability, which is precisely what this conference is about. We convene the very teams who use them. We'd love to have Widgit Health exhibit with us."],
];

// Tab-delimited (TSV) with a header row, so buildSponsorInviteRows maps columns
// by name and notes containing commas are not split.
export const PROSPECT_TARGETS_TSV =
  ["Company", "Contact", "Email", "Website", "Note"].join("\t") +
  "\n" +
  TARGETS.map((r) => r.join("\t")).join("\n");

// ───────────────────────────────────────────────────────────────────────────
// FOOD SPONSORS — Chicago vegan/vegetarian restaurants & caterers.
//
// The conference is fully plant-based (no meat served), so these are asked to
// donate or cater a meal in kind, and receive the dedicated food letter. Loaded
// with the "food" tier from the "Load food prospects" button.
//
// EMAILS ARE BLANK ON PURPOSE. This session's network policy blocked opening
// restaurant websites, so emails could not be verified. Every restaurant below
// is real and currently operating (identity/cuisine/details cross-checked via
// search; closures were screened out), but the contact email must be confirmed
// on each restaurant's own Contact/Catering page before sending. See
// docs/food-sponsor-prospects.md for the page to check per restaurant and the
// (unverified) candidate addresses search surfaced. FOOD_PROSPECT_TARGETS_TSV
// only includes rows whose Email has been filled in, so loading is safe.
// ───────────────────────────────────────────────────────────────────────────
const FOOD_TARGETS: Target[] = [
  ["The Chicago Diner", "", "orders@veggiediner.com", "https://veggiediner.com", "Meat-free since 1983, the Chicago Diner is practically the city's plant-based institution, from the Radical Reuben to those famous vegan shakes. A conference that has committed to an all-plant-based table would be proud to serve food from a kitchen that helped define vegetarian Chicago. We'd be honored to talk with you about catering a meal."],
  ["Handlebar", "", "info@handlebarchicago.com", "https://www.handlebarchicago.com", "For two decades Handlebar has shown Wicker Park that vegetarian comfort food can be the main event, with a sustainability ethic in how you source. That spirit fits a conference that chose to keep meat off the table entirely. We'd love to explore having you cater part of the weekend."],
  ["Soul Veg City", "", "loriseay10@gmail.com", "https://soulvegcity.com", "For more than forty years your Chatham kitchen has shown that soul food can be fully plant-based and deeply satisfying. As we put on an all-vegan conference, your by-the-pound spread would feed our attendees beautifully and tell a Chicago story worth telling. We'd be honored to talk catering."],
  ["Kale My Name", "", "gm@kalemyname.com", "https://www.kalemyname.com", "Kale My Name's globe-spanning vegan menu, from Mediterranean to Colombian to Balkan, mirrors the many cultures our conference brings together around language access. Your award-winning plant-based cooking would be a perfect fit for our all-vegan table. We'd love to talk about catering a meal."],
  ["Alice & Friends' Vegan Kitchen", "", "info@aliceandfriendsvegankitchen.com", "https://aliceandfriendsvegankitchen.com", "Alice & Friends has spent years serving Edgewater vegan comfort food drawn from cuisines all over the world, which is exactly the spirit of a conference built around reaching every community. As we keep our table fully plant-based, we'd be honored to feature your cooking. Could we talk about catering?"],
  ["Amitabul", "", "amitabill@gmail.com", "https://amitabulvegan.com", "Amitabul's Korean Buddhist cooking, rooted in dishes once made for monks, is plant-based in the most intentional sense, and unlike anything else in Chicago. For an all-vegan conference centered on cultural and language access, your food would mean a great deal. We'd love to talk about catering a meal."],
  ["Arya Bhavan", "", "aryabhavan@aol.com", "https://aryabhavan.com", "Since going fully vegan in 2013, Arya Bhavan has been a Devon Avenue anchor for whole-food, plant-based Indian cooking. A conference that has committed to an entirely meat-free table, and that celebrates Chicago's many cultures, would be honored to serve your food. Could we talk about catering?"],
  ["Penelope's Vegan Taqueria", "", "info@penelopesvegantaqueria.com", "https://penelopesvegantaqueria.com", "As Chicago's first fully plant-based taqueria, Penelope's makes exactly the kind of food a room full of people loves to share, and it happens to be entirely vegan. For our all-plant-based conference, a taco spread from your kitchen would be a joy. We'd love to talk about catering."],
  ["Urban Vegan", "", "urbanveganlp@gmail.com", "https://www.urbanveganthai.com", "Urban Vegan proves that Thai food loses nothing when it goes fully plant-based, which is the very case our all-vegan conference hopes to make. Your cooking would be a warm, flavorful fit for our attendees. Could we talk about catering a meal?"],
  ["Veggie House", "", "veggiehousechicago@gmail.com", "https://www.veggiehouseusa.com", "Veggie House brings fully plant-based Chinese cooking to the heart of Chinatown, mock-meat classics and all. As we put on an entirely vegan conference that celebrates Chicago's cultural breadth, your food would be a natural fit. We'd love to talk about catering."],
  ["Healthy Substance", "", "support@healthysubstance.com", "https://www.healthysubstance.com", "Healthy Substance shows Chicago that Mexican food can be fully plant-based without losing its soul, exactly the spirit of our all-vegan conference. Your cooking would feed our attendees well. Could we talk about catering a meal?"],
  ["Fancy Plants Catering", "", "fancyplantskitchen@gmail.com", "https://fancyplantscatering.com", "Fancy Plants is built for exactly what we need: a 100% vegan caterer with hundreds of multi-course dinners and festival services behind it. For our all-plant-based conference, your themed menus would be a tremendous fit. We'd love to talk about catering a meal."],
  ["Soul Vegan", "", "info@thesoulvegan.com", "https://soulvegan.com", "Soul Vegan calls itself Chicago's leader in sustainable soul food, and you cater plant-based events at real scale. For a conference that has committed to keeping meat off the table, that capacity is exactly what we're looking for. We'd be honored to talk catering."],
  ["Vegan Now 2 Go", "", "", "https://vegannow2go.com", "Vegan Now 2 Go carries decades of family plant-based recipes and a full bakery and catering kitchen behind the counter. For our all-vegan conference, your deli spreads and desserts would feed our attendees wonderfully. Could we talk about catering?"],
  ["Can't Believe It's Not Meat", "", "cantbelieveitsnotmeat@yahoo.com", "https://cantbelieveitsnotmeat.com", "Chef Laricia Baker Chandler built Can't Believe It's Not Meat into a vegan kitchen that caters corporate events and big gatherings, which is just what our all-plant-based conference needs. Your woman-owned, community-rooted story fits our mission, too. We'd love to talk about catering."],
  ["Vegan World Café", "", "elihu@veganworldcafe.com", "https://veganworldcafe.com", "Vegan World Café is, at heart, a plant-based soul-food catering company, run by chefs who have spent decades cooking vegan. For our all-vegan conference, catering is exactly the conversation we'd love to have with you. Could we find a time to talk?"],
  ["Pie, Pie My Darling", "", "piepiemydarling@gmail.com", "https://www.piepiemydarling.net", "Pie, Pie My Darling has been fully vegan since 2014, and your cakes and pastries would be a beautiful sweet note for our all-plant-based conference. We know desserts are pre-order pickup, and we'd gladly work around that. Could we talk about a dessert sponsorship?"],
  ["PLANTA Queen", "", "hellochicago@plantahq.com", "https://www.plantarestaurants.com", "PLANTA Queen shows that fully plant-based dining can be genuinely upscale, which is a message our all-vegan conference would be proud to carry. For a marquee meal or private-dining moment, your kitchen would be a standout. We'd love to explore what's possible."],
  ["Majani", "", "Majani7167@gmail.com", "https://majani.biz", "Majani's award-winning, Black-owned plant-based soul food has a story our conference would be honored to help tell. We understand the restaurant is on hiatus while you build the Vegan Village, and that catering continues, which is exactly what we'd hope to talk with you about."],
  ["The Vulgar Vegan", "", "order@thevulgarvegancupcakes.com", "https://thevulgarvegancupcakes.com", "The Vulgar Vegan makes the kind of cupcakes, and the specialty coffee, that a room full of people lights up over, all of it fully vegan. For our all-plant-based conference, a sweet table or coffee service from your woman-owned shop would be a treat. Could we talk about a dessert or coffee sponsorship?"],
  ["Vegan Plate", "", "veganplatelp@gmail.com", "https://veganplatecompany.com", "Vegan Plate proves that Thai food gives up nothing when it goes 100% plant-based, which is exactly the case our all-vegan conference hopes to make. Your Lincoln Park kitchen would be a flavorful fit for our attendees. We'd love to talk about catering a meal."],
  ["Beacon Doughnuts", "", "info@beacondoughnuts.com", "https://beacondoughnuts.com", "Every doughnut Beacon makes is vegan, from that 24-hour brioche dough on out, and a morning spread of them would be a joy for our attendees. For our all-plant-based conference, a breakfast or dessert sponsorship from you would be wonderful. Could we talk?"],
  ["Vaca's Creamery", "", "hello@vacascreamery.com", "https://vacascreamery.com", "As Chicago's first vegan soft-serve shop, Vaca's makes a dessert that delights everyone and happens to be fully plant-based and gluten-free. For our all-vegan conference, a sweet treat from your kitchen would be a lovely touch. We'd love to talk about a dessert sponsorship."],
  ["Elephant + Vine", "", "info@elephantandvine.com", "https://elephantandvine.com", "Elephant + Vine shows that fully plant-based fast-casual can be genuinely chef-crafted, which is the message our all-vegan conference is glad to carry. Your food would feed our attendees beautifully. We'd love to talk about catering a meal."],
  ["Annapurna Simply Vegetarian", "", "info@eatannapurna.com", "https://eatannapurna.com", "Since 1982, Annapurna has been one of Chicago's oldest fully vegetarian kitchens, an institution on Devon Avenue. For an all-plant-based conference that celebrates Chicago's many cultures, your Indian cooking would mean a great deal. We'd be honored to talk about catering."],
  ["Loving Heart Vegan Cafe", "", "lovingheartvegan1@gmail.com", "https://lovingheartvegan.com", "Loving Heart has been fully vegan since 2013, with sauces and salads made from scratch, exactly the care our all-plant-based conference is built around. Your Uptown kitchen would be a warm fit for our attendees. Could we talk about catering a meal?"],
  ["Cinnaholic Wicker Park", "", "Cinnaholic.WickerPark@gmail.com", "https://cinnaholicwickerpark.com", "Cinnaholic's build-your-own cinnamon rolls are 100% vegan, dairy and egg free, and a warm tray of them would delight our attendees. For our all-plant-based conference, a dessert or breakfast sponsorship from you would be a treat. Could we talk?"],
  ["Umami From Scratch", "", "contact@umamifromscratch.com", "https://umamifromscratch.com", "Umami From Scratch is a fully vegetarian, nut-free microbakery and caterer, the kind of careful, from-scratch kitchen our all-plant-based conference loves. Chef Divyasha's food would be a thoughtful fit for our attendees. We'd love to talk about catering."],
  ["B'Gabs Vegan Scratch Kitchen", "", "Bgabsvegankitchen@outlook.com", "https://bgabsgoodies.com", "B'Gabs serves fully vegan soul food, cooked and raw, from a Black-woman-owned Hyde Park kitchen with a story our conference would be honored to help tell. For our all-plant-based event, your cooking would feed our attendees wonderfully. Could we talk about catering?"],
];

// Only rows whose Email has been filled in are loadable (the rest are awaiting
// email verification, see the note above). Loaded with the "food" tier.
export const FOOD_PROSPECT_TARGETS_TSV =
  ["Company", "Contact", "Email", "Website", "Note"].join("\t") +
  "\n" +
  FOOD_TARGETS.filter((r) => r[2].trim()).map((r) => r.join("\t")).join("\n");
