// The 2024 conference roster — everyone who filled out the first joint
// conference's registration form (and/or appears in its payment report),
// parsed from the organizer's export. Loaded into the attendee pipeline via
// Attendees -> "Load 2024 roster"; each person gets the "returning" reunion
// letter, personalized with their 2024 mode and language pair.
//
//   status2024: "paid"      — registered AND paid in 2024 (real attendee)
//               "attempted" — started a 2024 checkout, never completed it
//               "lead"      — left their info only
//   mode2024:   "in-person" | "virtual" — how they attended or planned to.
//
// Counts at generation time: 501 people = 120 paid ($12,510 total),
// 66 attempted, 315 lead. 21 paid in person, 99 paid virtual.

export type Returning2024 = {
  firstName: string;
  lastName: string;
  email: string;
  languages: string;
  mode2024: "in-person" | "virtual" | "";
  status2024: "paid" | "attempted" | "lead";
};

export const RETURNING_2024: Returning2024[] = [
  { firstName: "Cynthia", lastName: "Anderson", email: "1cynthiaaanderson@gmail.com", languages: "english", mode2024: "virtual", status2024: "paid" },
  { firstName: "Aaqib", lastName: "Iqbal", email: "aaqibkureshi96@gmail.com", languages: "ENGLISH , URDU, PUNJABI", mode2024: "virtual", status2024: "lead" },
  { firstName: "Abby", lastName: "Ewing", email: "abbyewing7102@gmail.com", languages: "English and ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jocelyn", lastName: "Atienza-Alferez", email: "acesalferez@gmail.com", languages: "Tagalog/Pilipino", mode2024: "virtual", status2024: "lead" },
  { firstName: "Adnan", lastName: "Ahmad", email: "adnan.bach6@gmail.com", languages: "Pashto", mode2024: "virtual", status2024: "lead" },
  { firstName: "Adriana", lastName: "Gonzalez Diaz", email: "adriglez.diaz@gmail.com", languages: "Spanish/english", mode2024: "virtual", status2024: "paid" },
  { firstName: "Alicia", lastName: "Hart", email: "ahart315@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Chanwen", lastName: "Yao", email: "ahkw1985@gmail.com", languages: "Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Aida", lastName: "Couch", email: "aida.couch@cchmc.org", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Aida", lastName: "Menchaca", email: "aijavmac@hotmail.com", languages: "Spanish/English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Aisha", lastName: "Daoud", email: "aishasoliman782@gmail.com", languages: "Arabic", mode2024: "in-person", status2024: "lead" },
  { firstName: "Abdelshakour", lastName: "Khamis", email: "akhamis2009@gmail.com", languages: "Fur", mode2024: "in-person", status2024: "lead" },
  { firstName: "aktar Ismail", lastName: "Mohammad Ismail", email: "aktarismailunhcrinter@gmail.com", languages: "Rohingya and buremese", mode2024: "in-person", status2024: "lead" },
  { firstName: "aktar Ismail", lastName: "Mohammad Ismail", email: "aktarismialunhcrinter@gmail.com", languages: "Rohingya, Burmese", mode2024: "in-person", status2024: "lead" },
  { firstName: "Alejandra", lastName: "Dominguez", email: "alejandra.dominguez@achn.net", languages: "Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Alejandra", lastName: "Dominguez", email: "alejandrapedroza86@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ali", lastName: "Saeedi", email: "ali.saeedi@vumc.org", languages: "Arabic, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Alice", lastName: "Bendinelli", email: "alice@arcos.institute", languages: "Italian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Alla", lastName: "Lushnikova-Abbott", email: "allaabbott@gmail.com", languages: "Russian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Allie", lastName: "Hammond", email: "alliebhammond@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Allison", lastName: "Henry", email: "allison.d.henry@vanderbilt.edu", languages: "English, Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Alma", lastName: "Delgado", email: "almadelgado1@aol.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Alyaa", lastName: "Murad Abd", email: "alyaa.muradaa@outlook.com", languages: "Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Amani", lastName: "Zaki", email: "amani_nader@hotmail.com", languages: "Arabic. English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Miriam", lastName: "Amaya", email: "amayamiriam11@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Amel", lastName: "Kh", email: "amel2020philly@gmail.com", languages: "Berber", mode2024: "virtual", status2024: "attempted" },
  { firstName: "America", lastName: "Moreno", email: "amica002@yahoo.com", languages: "English/Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Blanca", lastName: "Pacheco", email: "amlebr302514@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Amr Yahya", lastName: "Sayed", email: "amr.yahya01@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "\u00c1ngel", lastName: "Montilla Su\u00e1rez", email: "amsuarezlsipmar@gmail.com", languages: "Spanish, English, Brazilian Portuguese, Sign Language, Hebrew", mode2024: "virtual", status2024: "lead" },
  { firstName: "Analynda", lastName: "Eng", email: "analynda.eng@gmail.com", languages: "Khmer", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ana Maria", lastName: "Studer", email: "anamaria.studer@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Adriana", lastName: "Andrade Moreno", email: "andrade376@gmail.com", languages: "Spanish and English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Yara", lastName: "Andrade", email: "andradeyara628@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Anxin", lastName: "Chen", email: "anduminchen@outlook.com", languages: "Mandarin, English, Cantonese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Anibal", lastName: "D\u00e1vila de leon", email: "anibaldavila95@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Anita", lastName: "Coelho", email: "anita.c.diabate@gmail.com", languages: "English/Portuguese", mode2024: "virtual", status2024: "paid" },
  { firstName: "Anylu A", lastName: "Nerio", email: "anylu.neriogarza@cookchildrens.org", languages: "English/Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Angelica", lastName: "Olivas", email: "aolivas@kcpublicschools.org", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Angelica", lastName: "Paredes", email: "aparede@cookcountyhhs.org", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Araminta", lastName: "Hawkins", email: "ari4homes@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Arianna", lastName: "Vivas", email: "Arianna.c.vivas@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Alicia", lastName: "Roeth", email: "aroeth@childrensnebraska.org", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Alejandra", lastName: "Aguirre", email: "artetolteca@gmail.com", languages: "Spanish/English", mode2024: "virtual", status2024: "lead" },
  { firstName: "ARIF", lastName: "OMAR", email: "aruuf23@gmail.com", languages: "Somali", mode2024: "virtual", status2024: "lead" },
  { firstName: "Adam", lastName: "Samko", email: "asamko@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "sad", lastName: "asd", email: "asd@aalb.org", languages: "sadas", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ashley", lastName: "Mendez", email: "ashleysmendez@gmail.com", languages: "English; Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Aida", lastName: "Sanchez", email: "asm3nenes@gmail.com", languages: "English, Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Asmaa", lastName: "Abbou Chaar", email: "asmosh79@gmail.com", languages: "Arabic/English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Avinash", lastName: "Srinadhu", email: "avinashsrinadhu90@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Shireen", lastName: "Awwad", email: "awwadshireen8@gmail.com", languages: "English _arabic", mode2024: "in-person", status2024: "lead" },
  { firstName: "Gabriela", lastName: "Olguin", email: "aye_2000@yahoo.com", languages: "English and Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ivenitza", lastName: "Ortiz", email: "aztinevi@hotmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Barlla", lastName: "Nascimento", email: "barlla2002@hotmail.com", languages: "Portuguese", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Marcia", lastName: "Cattles", email: "bellamarciamaria@gmail.com", languages: "English Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ben", lastName: "Min", email: "ben871313@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Bielca", lastName: "Guevara", email: "bielcarodriguez@hotmail.com", languages: "spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Patricia", lastName: "Landaverry", email: "bilingualbridgeint@gmail.com", languages: "Spanish/English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Beatriz", lastName: "Jatem", email: "bjatem@gmail.com", languages: "English and Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Blanca Leticia", lastName: "Merlin Jarquin", email: "blanca.leticia.merlin@gmail.com", languages: "English-Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Brae", lastName: "Wah", email: "brae.wah@outlook.com", languages: "Karen/Burmese", mode2024: "virtual", status2024: "paid" },
  { firstName: "Brenda", lastName: "Ortiz Zamora", email: "brenda.ortiz75@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Brenda", lastName: "MacDonald", email: "brendam@flchealth.org", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Adriana", lastName: "Sanchez", email: "bridgingap0@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Brittany", lastName: "Ford", email: "brittany.ford@gmail.com", languages: "English", mode2024: "in-person", status2024: "paid" },
  { firstName: "Heidy", lastName: "Torres", email: "brownvheidy@gmail.com", languages: "Spanish/english", mode2024: "virtual", status2024: "lead" },
  { firstName: "Carina", lastName: "Bedoya", email: "carinamaciel2018@outlook.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "carla", lastName: "TORANZO", email: "carla.toranzo@hotmail.com", languages: "spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Carla", lastName: "Breckenridge", email: "carlabreckenridge123@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Carlos", lastName: "Olvera", email: "carlos_olvera@rush.edu", languages: "Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Eusebio", lastName: "Castillo", email: "castiloe@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Carolina", lastName: "Conde", email: "ccondeo@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Celines", lastName: "Ramos", email: "celines.ramos@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Charlene", lastName: "Shih", email: "charleneshih@yahoo.com", languages: "Chinese Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Yao", lastName: "Chen", email: "charleschenyao@gmail.com", languages: "Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rosalia", lastName: "Bautista", email: "chicago_63@hotmail.com", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Maria isabel", lastName: "Joseph", email: "chicavelasco@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Connie", lastName: "Hincapie", email: "chincapie1010@gmail.com", languages: "Spanish-English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Cindy", lastName: "Hou", email: "cindy.hou@jefferson.edu", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Citlali", lastName: "Ochoa", email: "citla.salazar8a@gmail.com", languages: "Spanish, English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Claudia", lastName: "Guerrero Barrera", email: "claudia.guerrero-barrera@vdh.virginia.gov", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Claudia", lastName: "Rosales Mejia", email: "cmsandoval220@aol.com", languages: "Spanish/English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Connie", lastName: "Tsai", email: "connie.tsai@gmail.com", languages: "English, Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Constantina", lastName: "Baldwin", email: "Constantina.Baldwin@mlh.org", languages: "Spanish; Greek", mode2024: "virtual", status2024: "paid" },
  { firstName: "Carla", lastName: "Shah", email: "cshah@csb-cde.ca.gov", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Carlos", lastName: "Spinola", email: "cspinola422@gmail.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Carmen", lastName: "Velez", email: "cvelez1967@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "stefanie", lastName: "wang", email: "cwang237@uic.edu", languages: "english", mode2024: "in-person", status2024: "lead" },
  { firstName: "Steve", lastName: "Cyezi Nemeye", email: "cyezisteve@gmail.com", languages: "English", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Cecilia", lastName: "Galindo", email: "Cygalindo26@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Donna", lastName: "Abourass", email: "dabourass@hotmail.com", languages: "Arabic", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Osama", lastName: "Khan", email: "dafiyah.ls16@gmail.com", languages: "Urdu and Punjabi", mode2024: "virtual", status2024: "lead" },
  { firstName: "Daniel", lastName: "Dickover", email: "danattippe@gmail.com", languages: "English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ruth D", lastName: "Lopez Gaitan", email: "daneli05@yahoo.com", languages: "(505) 306-7633", mode2024: "virtual", status2024: "paid" },
  { firstName: "Daniel", lastName: "Hsueh", email: "danhsueh@gmail.com", languages: "Mandarin and Cantonese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Daniela", lastName: "Benner", email: "daniela.benner@summitstonehealth.org", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Daniela", lastName: "Cazares", email: "danielaczrs15@gmail.com", languages: "Spanish", mode2024: "in-person", status2024: "attempted" },
  { firstName: "David", lastName: "Retamar", email: "daret77@aol.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Darien", lastName: "Chandler", email: "darienmejia.s@gmail.com", languages: "Spanish & English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Darren", lastName: "Reed", email: "darren@aalb.org", languages: "English, Spanish, ASL", mode2024: "virtual", status2024: "paid" },
  { firstName: "David", lastName: "Eddington", email: "david.eddington@vcuhealth.org", languages: "English, Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Lansa", lastName: "Dawano", email: "dawano014@gmail.com", languages: "English, Oromo, Amharic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Diana", lastName: "Diaz", email: "ddiaz2018@yahoo.com", languages: "Spanish, English", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Dena", lastName: "Karakoshi Hanania", email: "deenawfp@yahoo.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Gabriela", lastName: "De La Vega", email: "delavegagaby@yahoo.com", languages: "Spanish", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Denise", lastName: "Muro", email: "denise@found-in-translation.org", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Yasmeen", lastName: "Metwally", email: "dentist.yasmeen@gmail.com", languages: "Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Deyanira", lastName: "De Leon", email: "deyaniradeleon@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Dinorah", lastName: "Gallegos", email: "DG.INTERP@GMAIL.COM", languages: "English and Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Di", lastName: "Shao", email: "di-s@outlook.com", languages: "French", mode2024: "virtual", status2024: "lead" },
  { firstName: "Diana", lastName: "Harmouch", email: "diana.harmouch@gmail.com", languages: "Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Diana", lastName: "Morales", email: "diana.moralessalcedo@choa.org", languages: "Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Diana", lastName: "Arce", email: "dianaarce1@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Diana", lastName: "Stanford Nasrallah", email: "dianastanford46@gmail.com", languages: "Spanish-English", mode2024: "virtual", status2024: "lead" },
  { firstName: "MARIAELENA", lastName: "MENJIVARDIAZ", email: "diazjmd04@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Elias", lastName: "Vald\u00e9s \u00c1lvarez", email: "dorianne497@yahoo.com", languages: "English, Spanish, Portugu\u00eas", mode2024: "virtual", status2024: "lead" },
  { firstName: "Mohammed amine", lastName: "Benaribi", email: "dr.mohammed_amine@yahoo.fr", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Dul\u00e8ne", lastName: "Mo\u00efse", email: "duleneema@gmail.com", languages: "Haitian Creole, French", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Sanjoy", lastName: "Dutt", email: "duttasanjay63@yahoo.com", languages: "Bengali", mode2024: "virtual", status2024: "lead" },
  { firstName: "david", lastName: "vazquez", email: "dxvazque@Ascension.org", languages: "spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Carla", lastName: "Farfan", email: "e.farfan88@hotmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Emily", lastName: "Borja", email: "eborja@stanfordchildrens.org", languages: "English", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Elizabeth Christian Cruz", lastName: "O'Malley", email: "ecmc8_1119@yahoo.com", languages: "TAGALOG FILIPINO & ILOCANO", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Eden", lastName: "Bravo Montenegro", email: "eden@cadizbaleares.com", languages: "Spanish; French", mode2024: "virtual", status2024: "lead" },
  { firstName: "Edolina", lastName: "Blaise", email: "edolina_blaise@yahoo.com", languages: "Haitian Creole", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Efrain", lastName: "Rodriguez", email: "efrain_r@live.com", languages: "ASL, Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ezechiel", lastName: "Philippe", email: "ejeanphilippe98@gmail.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Elena", lastName: "Gomez", email: "elenaluzgomez@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Elis", lastName: "Romero-Williams", email: "elis.romero2380@yahoo.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Elizabeth", lastName: "Armenta-Morales", email: "elisaarmenta1975@icloud.com", languages: "English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Elizabeth", lastName: "Narvaez", email: "elizabet.narvaezluna@gmail.com", languages: "Espa\u00f1ol", mode2024: "in-person", status2024: "lead" },
  { firstName: "Elizabeth", lastName: "Zamudio", email: "elizabeth.zamudio@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Elizabeth", lastName: "Neaves", email: "elizabethneaves1@gmail.com", languages: "English, Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "yu", lastName: "hong", email: "elliotatwork@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria Eloisa", lastName: "Leiva", email: "eloisa.leiva@medstar.net", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Emilia", lastName: "Riccio-Weiner", email: "emirw@aol.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Emmeline", lastName: "Startt", email: "emmelinestartt@gmail.com", languages: "English-Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Emmanuel", lastName: "Nsengiyumva", email: "emmy.interp@gmail.com", languages: "English and Kinyarwanda", mode2024: "virtual", status2024: "lead" },
  { firstName: "Lesa", lastName: "Tiatia", email: "empowered2servelt@gmail.com", languages: "Samoan", mode2024: "virtual", status2024: "lead" },
  { firstName: "Emilix", lastName: "Lli", email: "enll7@aol.com", languages: "Spanish / English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Eduardo", lastName: "Nunez", email: "enunez0588@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Eric", lastName: "Cardenas", email: "eric.cardenas@utrgv.edu", languages: "ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Eric", lastName: "Espinoza", email: "ericespinoza9800@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Erika", lastName: "Graham", email: "Erika12376@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Erika", lastName: "Pena", email: "erikaerik390@gmail.com", languages: "Spanish /english", mode2024: "virtual", status2024: "lead" },
  { firstName: "Erika", lastName: "Hernandez", email: "erikarod2000@yahoo.com", languages: "English- Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Esperanza", lastName: "Walle", email: "esperanza.walle@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Esther", lastName: "Lim", email: "esther.lim365@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Saira", lastName: "Estrada", email: "estradasaira@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Estrella", lastName: "Gancedo Gordillo", email: "estrella.gancedo@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Eva", lastName: "Mwariri", email: "eva.mwariri@gmail.com", languages: "Swahili,Gikuyu, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Evelyn", lastName: "Gutierrez", email: "evelyng5@g.ucla.edu", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Michelle", lastName: "Sun", email: "evermavcapital@gmail.com", languages: "Chinese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Erica", lastName: "Vidrio", email: "evidrio17@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Fatima", lastName: "Correia", email: "Facorreia26@gmail.com", languages: "portuguese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Fatima", lastName: "Gutierrez", email: "fatimagutierrezmo@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Fawad", lastName: "Afzal", email: "fawadkhan127656@gmail.com", languages: "Pashto", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Sahibzada Fahad", lastName: "Bacha", email: "fbacha415@gmail.com", languages: "Pashto", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Foudil", lastName: "Belfa", email: "fdlbelfa@yahoo.fr", languages: "French, Arabic, English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Heidy Francesca", lastName: "Calderon", email: "francesca_calderon@live.com", languages: "English and Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Amparo", lastName: "Franco", email: "francoampaint17@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Abdoulaye", lastName: "Gueye", email: "francoarabe2003@yahoo.fr", languages: "French/English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Frida", lastName: "Ballard", email: "frida.ballard@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Abdelshakoaur", lastName: "M. Khamis", email: "furcommunityny@gmail.com", languages: "Fur", mode2024: "virtual", status2024: "lead" },
  { firstName: "Geraldine", lastName: "Casimiro", email: "g.geraca@gmail.com", languages: "Spanish & English", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Gabriela", lastName: "Siebach", email: "gabriela.siebach@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ganerdene", lastName: "Gantumur", email: "gan@mongoltranslator.com", languages: "Mongolian", mode2024: "in-person", status2024: "paid" },
  { firstName: "Dora", lastName: "Ortiz", email: "gdortiz13@msn.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Gabriela", lastName: "Duarte-Lopez", email: "gdrtlpz@yahoo.com", languages: "English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Geisa", lastName: "Williams", email: "geisacristina7@gmail.com", languages: "Portuguese/English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Geraldine", lastName: "Landry", email: "geralarte@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Agnes", lastName: "Guegue", email: "gggue@yahoo.com", languages: "French ,Ewe", mode2024: "virtual", status2024: "lead" },
  { firstName: "Gary", lastName: "Hanes", email: "ghanes1965@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "GISSEL", lastName: "BARBECHO", email: "gissebh1991@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Gloria", lastName: "Ortega-Gerdts", email: "gl.ortega01@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "GLADYS", lastName: "VALENZUELA", email: "gladys.araizav@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Gerardo", lastName: "Lazaro", email: "glazaro@hotmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Blanca", lastName: "Gonzalez", email: "gonzalezby91@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Said", lastName: "gardaad", email: "gowlale@gmail.com", languages: "Somali", mode2024: "virtual", status2024: "lead" },
  { firstName: "Clara", lastName: "Gracia", email: "gracia.clara1998@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Griselda", lastName: "Myrcia", email: "griseldalopez901@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Geysa", lastName: "Rodriguez", email: "grtranserv@ptd.net", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Guadalupe", lastName: "Garcia", email: "guadalupe.garcia@cookcountyhealth.org", languages: "Spanish", mode2024: "in-person", status2024: "attempted" },
  { firstName: "guilus", lastName: "schultz", email: "guilus@icloud.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Gulya", lastName: "Shigabutdinova", email: "gulya.shigabutdinova@gmail.com", languages: "English, Russian", mode2024: "virtual", status2024: "paid" },
  { firstName: "Reyna", lastName: "Moretta", email: "gus_reyna@att.net", languages: "Spanish, Eng\u00f1ish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Gulnara", lastName: "Schroer", email: "guschroer@gmail.com", languages: "Russian", mode2024: "virtual", status2024: "paid" },
  { firstName: "Ingrid", lastName: "Guzman", email: "Guzmaningrid393@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "chuling", lastName: "zong", email: "gxl201001@yahoo.com", languages: "mandarin", mode2024: "virtual", status2024: "paid" },
  { firstName: "Abdulhaleem", lastName: "Sioty", email: "Haleem.sioty@gmail.com", languages: "Arabic", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Hanh", lastName: "Leforhan", email: "hanhleforhan@icloud.com", languages: "Vietnamese", mode2024: "virtual", status2024: "paid" },
  { firstName: "Haidy", lastName: "Beshara", email: "hbeshara@stratusvideo.com", languages: "Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Heather", lastName: "Thomas", email: "heathercanny@protonmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "x", lastName: "x", email: "hello@yahoo.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Hindi", lastName: "Ali", email: "hindomc99@gmail.com", languages: "Somali", mode2024: "virtual", status2024: "paid" },
  { firstName: "Hiroko", lastName: "Harada", email: "hirokox77@hotmail.com", languages: "Japanese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Huilin", lastName: "Gao", email: "huilin.alex.gao@gmail.com", languages: "Mandarin", mode2024: "in-person", status2024: "paid" },
  { firstName: "KE", lastName: "HUYNH", email: "huynhke@hotmail.com", languages: "Vietnamese", mode2024: "virtual", status2024: "lead" },
  { firstName: "HaEl", lastName: "Pham", email: "hzlwn52@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Hilda", lastName: "Ibarra", email: "ibarrahilda362@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Idolly", lastName: "Oliva", email: "idolly.oliva@fairview.org", languages: "spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Ileana", lastName: "Keller", email: "ileana.keller@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ileana", lastName: "Fiola", email: "ileanafiola11@gmail.com", languages: "English .. Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ilona", lastName: "Kmit", email: "ilonakmit96@gmail.com", languages: "Ukrainian and Russian", mode2024: "in-person", status2024: "lead" },
  { firstName: "INMACULADA", lastName: "MONTELLS-MURIITHI", email: "immamontells@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Sandy", lastName: "Mejia", email: "INTERPRETERSANDYMEJIA@GMAIL.COM", languages: "SPanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Iryna", lastName: "Isayeva", email: "iraisayeva@gmail.com", languages: "Ukrainian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Irfan", lastName: "Ahmad", email: "irfanahmad22999@gmail.com", languages: "Pashto", mode2024: "virtual", status2024: "lead" },
  { firstName: "Caroline", lastName: "Isaac", email: "isaacarolined@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Isabel", lastName: "Braithwaite", email: "isabel.braithwaite@comcast.net", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "MIRALEM", lastName: "ISAKOVIC", email: "Isakovic24@gmail.com", languages: "Bosnian, Croatian, Montenegrin, Serbian", mode2024: "in-person", status2024: "paid" },
  { firstName: "Dong", lastName: "Isbister", email: "isbisterd@uwplatt.edu", languages: "Chinese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Itedal", lastName: "Shalabi", email: "ishalabi@aafsil.org", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Israa", lastName: "Abdulsahib", email: "israabdulhadi@yahoo.com", languages: "Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ivan", lastName: "Ortiz", email: "ivanortiz400@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Jacqueline", lastName: "Ngo", email: "jackiebuingo@gmail.com", languages: "Vietnamese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jacqueline", lastName: "Holcomb", email: "jacqueline85706@gmail.com", languages: "Vietnamese", mode2024: "virtual", status2024: "paid" },
  { firstName: "Jairo", lastName: "Suarez", email: "jairo14suarez@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jannia", lastName: "Valencia", email: "janniahv@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Jacqueline", lastName: "Forsythe", email: "jaqforsythe@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Ernestina", lastName: "Jara", email: "jaraernestina@yahoo.com", languages: "Spanush", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jared", lastName: "Beebe", email: "jaredmbeebe@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Jessica", lastName: "Armenta", email: "jarmenta@cmc-sc.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Jean Claude", lastName: "Zidor", email: "jczidor@gmail.com", languages: "Haitian Creole", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jeanette", lastName: "Zaragoza", email: "jeanette.zaragoza@upr.edu", languages: "SPAN", mode2024: "virtual", status2024: "paid" },
  { firstName: "Jesenia", lastName: "Delgado De Jesus", email: "jesenia.delgado11@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jesse", lastName: "Youngblood", email: "jesseyoungbloodinterpreting@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jessica", lastName: "Daniels", email: "jessica@helpinghandshawaii.org", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jesus", lastName: "Del Toro", email: "jesus.deltoro@cityofchicago.org", languages: "English, Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Karina", lastName: "Gamboa", email: "jfer.kari994@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jie", lastName: "Young", email: "jiecyoung@gmail.com", languages: "Mandarin, Cantonese", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Jimmy", lastName: "Guerrier", email: "jimor.ronald@gmail.com", languages: "Haitian creole", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Jinhi", lastName: "Roskamp", email: "jinhiroskamp@outlook.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jo", lastName: "Bertloff", email: "jobe216@gmail.com", languages: "English/ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Devanee", lastName: "Orellana", email: "Jocelineflores28@gmail.com", languages: "Spanish,english", mode2024: "in-person", status2024: "lead" },
  { firstName: "Johana", lastName: "Munoz Lopez", email: "johanacm518@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Johanna", lastName: "Vega", email: "Johannavegausac@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Joshua", lastName: "Collier", email: "joshua@connxus.org", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Josie", lastName: "Easton", email: "josieeaston1@gmail.com", languages: "ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Joyce", lastName: "Renderos Narvaez", email: "jrenderos@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Janina", lastName: "Sulca", email: "jsulca@bhs1.org", languages: "Sanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "James", lastName: "Tyson-Channer", email: "jtchannerllc@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Julia", lastName: "Fig", email: "julia.fig.701005@stratusvideo.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Julia", lastName: "Ledesma de Rusinol", email: "juliarusinol.spanish@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Karina", lastName: "Sesso", email: "karina.sesso@yahoo.com", languages: "EN-SP", mode2024: "virtual", status2024: "lead" },
  { firstName: "Karla", lastName: "Grathler", email: "karla.grathler@siu.edu", languages: "English", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Katelin", lastName: "Cruz", email: "Kateandel@att.net", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Katharine", lastName: "Allen", email: "katharine.allen@boostlingo.com", languages: "English / Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Kathy", lastName: "Sliwinski", email: "kathy.sliwinski@northwestern.edu", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Katiuska", lastName: "Gamez Canizalez", email: "katigamez81@gmail.com", languages: "English, Spanish, French, Italian", mode2024: "virtual", status2024: "paid" },
  { firstName: "Kay", lastName: "Davenport", email: "kay@swvainterpreter.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Kayleigh", lastName: "Avila", email: "kayleigh.a.avila@gmail.com", languages: "English, ASL", mode2024: "virtual", status2024: "paid" },
  { firstName: "Kelley", lastName: "Walton", email: "kelley.walton@uoflhealth.org", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Kevin", lastName: "Datwyler", email: "kevin.j.datwyler@gmail.com", languages: "English and Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Khaled", lastName: "Metwaly", email: "khaledelnubi@gmail.com", languages: "Arabic", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Antoine Kevin", lastName: "Kinzimou Mantsounga", email: "kinzimoukevin12345@gmail.com", languages: "French", mode2024: "virtual", status2024: "lead" },
  { firstName: "Koffi", lastName: "Mahouna", email: "kmahouna@gmail.com", languages: "French", mode2024: "virtual", status2024: "lead" },
  { firstName: "Kim", lastName: "Mihan", email: "kmihan23@gmail.com", languages: "Asl", mode2024: "virtual", status2024: "lead" },
  { firstName: "Kate", lastName: "Ramirez", email: "ksrr0607@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Laura", lastName: "Cranston", email: "laura.cranston@centracare.com", languages: "English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Laura", lastName: "Puls", email: "laurampuls@gmail.com", languages: "English", mode2024: "in-person", status2024: "paid" },
  { firstName: "Laurie", lastName: "Albritton", email: "laurie.b.albritton@vumc.org", languages: "English / Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Danielo", lastName: "Leger", email: "legerdanielo@gmail.com", languages: "Haitian creole", mode2024: "virtual", status2024: "lead" },
  { firstName: "Lennore", lastName: "Vinnie", email: "lennore.vinnie@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Leonardo", lastName: "Mahecha", email: "leomahecha.c@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Adjo", lastName: "Agbossoumonde", email: "leponttranslations@gmail.com", languages: "Ewe, French, English proficiency", mode2024: "virtual", status2024: "lead" },
  { firstName: "Thi Khuyen", lastName: "Le", email: "lethikhuyen111@gmail.com", languages: "Vietnamese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Leticia", lastName: "Besker", email: "leticia.besker@hotmail.com", languages: "Brazilian Portuguese, En", mode2024: "virtual", status2024: "paid" },
  { firstName: "Laura", lastName: "Cooley", email: "lgcooley88@gmail.com", languages: "Spanish\\English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Li", lastName: "Guo Camiro", email: "licamiro3@aol.com", languages: "Chinese Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Elnise", lastName: "Diaz", email: "lidiediaz8@gmail.com", languages: "Spanish/English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Shanna", lastName: "Lihnakevic", email: "likhnyakevich@yahoo.com", languages: "Russian/Ukrainiane", mode2024: "virtual", status2024: "paid" },
  { firstName: "Liliana", lastName: "Mercado", email: "liliana.mercado@rocketmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Lilian", lastName: "Aguiriano", email: "lilianaguiriano@gmail.com", languages: "spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Liliana", lastName: "Dinu", email: "liliandinu@hotmail.com", languages: "Spanish, Romanian, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "li", lastName: "fiorello", email: "liliruolan@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Ana", lastName: "Lima", email: "limannyh@gmail.com", languages: "Portuguese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Linda", lastName: "Yousif", email: "linday83@gmail.com", languages: "English, Arabic, Assyrian", mode2024: "virtual", status2024: "paid" },
  { firstName: "Bunderlai", lastName: "Souto Dunham", email: "linkterralanguages@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Marvin", lastName: "Lira", email: "liramarvin@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Angela", lastName: "Villareal", email: "littlemorlock@gmail.com", languages: "ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Laura", lastName: "Oliver", email: "loliver@chla.usc.edu", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Marina", lastName: "Godinez-Rodriguez", email: "lopezgodinez428@hotmail.com", languages: "English/Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "javier", lastName: "lopez lopez", email: "Lopezjavier1988@gmail.com", languages: "spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria", lastName: "Gomez", email: "lorenasalas0788@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Laurna", lastName: "Vasquez", email: "lorvasq@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria", lastName: "Ramirez", email: "lourdesbastian@gmail.com", languages: "Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Raquel", lastName: "Kline", email: "lsnfortwayne@yahoo.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Luc\u00eda", lastName: "Morales Carnicero", email: "luciamoralescarnicero@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Lu", lastName: "Zhu", email: "luzhu1207@gmail.com", languages: "Mandarin", mode2024: "virtual", status2024: "paid" },
  { firstName: "Leslie", lastName: "Walker", email: "lwalker@publichealthmdc.com", languages: "English, Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Lyan", lastName: "Basora Dorville", email: "Lyan.basora@gmail.com", languages: "Spanish, English", mode2024: "in-person", status2024: "paid" },
  { firstName: "Carolina", lastName: "Valero", email: "macarolavl@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria", lastName: "LeVering", email: "macbka87@gmail.com", languages: "Russian", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maria", lastName: "Tineo", email: "mafatrin@yahoo.com", languages: "Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Maha", lastName: "El-Attar", email: "Maha.el-attar@childrens.harvard.edu", languages: "Arabic/ English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Makenzie", lastName: "Lyon", email: "makenzie.lyon@uhkc.org", languages: "English, Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Lana", lastName: "Malki", email: "malki2005@gmail.com", languages: "Arabic", mode2024: "virtual", status2024: "paid" },
  { firstName: "Milagros", lastName: "Amaro", email: "mamaro@guilfordcountync.gov", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Mauricio", lastName: "Amaya", email: "mamaya96@icloud.com", languages: "English - Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Maria", lastName: "Anello", email: "manello@languageworld.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Manuel", lastName: "Zuniga", email: "manuel.b.zuniga@state.mn.us", languages: "English, Filipino", mode2024: "virtual", status2024: "paid" },
  { firstName: "mara", lastName: "De la Llata", email: "maradelallata@yahoo.com", languages: "spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Marcela", lastName: "Boyd", email: "marcela_boyd@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Nadia", lastName: "Crank", email: "marco_nadia@hotmail.com", languages: "Arabic", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maria", lastName: "Grant", email: "maria.grant@vumc.org", languages: "English & Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maria", lastName: "Mora", email: "maria.mora.700463@stratusvideo.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maria", lastName: "Hernandez", email: "maria.ramos7073@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maria A.", lastName: "Lliguichuzhca Duman", email: "mariagusta12@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria Isabel", lastName: "Garza", email: "mariai652004@gmail.com", languages: "Spanish/English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maria", lastName: "Michalczyk", email: "mariam@easystreet.net", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "MARIANA", lastName: "RUIZ GARCIA", email: "marianaruiz1982@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "MARIANA", lastName: "RUIZ GARCIA", email: "marianaruiz1982@hotmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "maria", lastName: "pena", email: "mariap@ncphd.org", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria", lastName: "Phipard", email: "mariaphipard@yahoo.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Maribel", lastName: "Fiol", email: "maribel.fiol@mountsinai.org", languages: "Spanish", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Marie Paule", lastName: "Laveaux Desir", email: "mariepaulelaveaux@yahoo.fr", languages: "Haitian Creole", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Teresa", lastName: "Marin Guzman", email: "marin.teresa87@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Alicia", lastName: "Nunez", email: "marthaalicianunez@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Martha", lastName: "Teissier", email: "marthateissier@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Marvin", lastName: "Matarrita", email: "marvinmata2001@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Mary", lastName: "Aina", email: "maryainable@gmail.com", languages: "English and French", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Maryam", lastName: "Badiee", email: "Maryambal100@gmail.com", languages: "English-Farsi/Persian", mode2024: "in-person", status2024: "lead" },
  { firstName: "David", lastName: "Bozone", email: "mattbozone@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maylin", lastName: "Torres", email: "maylin.torres@usa.genesiscare.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Natina", lastName: "McAndrews", email: "mcandrewsnatina@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Martina", lastName: "Cota", email: "mcota@phoenixchildrens.com", languages: "English Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Gerardo", lastName: "Hernandez", email: "me@ghernandez.net", languages: "English | Spanish", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Meg", lastName: "Rector", email: "meglrector@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Melanie", lastName: "Snellings", email: "melaniesnellings@gmail.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Melinda", lastName: "Vue", email: "melinda.vue@allina.com", languages: "Hmong", mode2024: "virtual", status2024: "paid" },
  { firstName: "Jace", lastName: "Norton", email: "mgmt@mayabridge.org", languages: "English", mode2024: "in-person", status2024: "paid" },
  { firstName: "Ludmila", lastName: "Golovine", email: "mgolovine@masterword.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Michelle", lastName: "Hsu", email: "michelle_hsu@msn.com", languages: "English, Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Francis", lastName: "Sanchez", email: "midory_18@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Mirha", lastName: "khalid", email: "mirha_khalid2000@hotmail.com", languages: "Urdu, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Mirna", lastName: "Stevens", email: "mirnastevens@gmail.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Becatrie", lastName: "Pierre louis", email: "misslorsa09@gmail.com", languages: "French", mode2024: "virtual", status2024: "lead" },
  { firstName: "Michelle", lastName: "Vanderpool", email: "mjcrawfo88@gmail.com", languages: "English/ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Kathleen", lastName: "Lanker", email: "MKLanker@sbcglobal.net", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Maria", lastName: "Jarquin-Lesky", email: "mlesky1216@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Monique", lastName: "Villaescusa", email: "monique33v@hotmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Yoni", lastName: "Miranda", email: "monjita2@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Monserrat", lastName: "Valencia", email: "monserratvalencia.interpreter@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Corina", lastName: "Ramirez", email: "morenaness33@gmail.com", languages: "English and Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jonathan", lastName: "Garcia", email: "mrcurypowr@hotmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Dr. Magdalena", lastName: "Rivera", email: "mrivera@illinoismigrant.org", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "MIREYA", lastName: "RENTERIA", email: "mryeya05@gmail.com", languages: "Spanish/English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Cinthia", lastName: "Lopez", email: "ms.cjlo0623@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rocio", lastName: "Alva", email: "ms_palencia_15@yahoo.com", languages: "Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Meredith", lastName: "Stegall", email: "mstegall@parasandassociates.net", languages: "English", mode2024: "in-person", status2024: "paid" },
  { firstName: "Lien", lastName: "Huynh", email: "mylienhuynh@yahoo.com", languages: "Vietnamese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ricardo", lastName: "Fuentes", email: "nacho620@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Nadia", lastName: "Crank", email: "nadia.o.crank@vumc.org", languages: "Arabic", mode2024: "virtual", status2024: "attempted" },
  { firstName: "nadia", lastName: "nuebling", email: "nadia@nuebling.us", languages: "Spanish-English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Nahomy", lastName: "Feliciano", email: "nahomy_feliciano@att.net", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Meghala", lastName: "Nalla", email: "nallameghalareddy@gmail.com", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Nallely", lastName: "Guti\u00e9rrez", email: "nallegutierrez@gmail.com", languages: "Spanish, Zapotec and English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Nancy", lastName: "Imbert", email: "nancyimbert41@gmail.com", languages: "French , Haitian Creole", mode2024: "virtual", status2024: "lead" },
  { firstName: "Nasiba", lastName: "Abdullaeva", email: "nasiba69@yandex.ru", languages: "Russian, Uzbek", mode2024: "in-person", status2024: "lead" },
  { firstName: "Nancy", lastName: "De La Cruz Pitones", email: "ndelacruz_1031@yahoo.com", languages: "English/Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Nidia", lastName: "Warner", email: "nidia.p.reyes@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Nikki", lastName: "Kao", email: "Nikkikao1@gmail.com", languages: "Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Nimo", lastName: "Yonis", email: "nimoy32@hotmail.com", languages: "Somali", mode2024: "virtual", status2024: "lead" },
  { firstName: "Nadia", lastName: "Saleh", email: "nino.s@live.com", languages: "Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Noe", lastName: "Azpeitia", email: "noe.azpeitia@luhs.org", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Noel", lastName: "Salcedo", email: "noelsjr@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Noemi Glendy Adelina", lastName: "Carrillo Martin", email: "noemicarrillomartin1@gmail.com", languages: "Mam", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Noe", lastName: "Neaves", email: "noeneavesjr@gmail.com", languages: "English, Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Ngoc", lastName: "Nguyen", email: "ntnguye04@gmail.com", languages: "English & Vietnamese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Olga", lastName: "Contreras Amador", email: "ocontreras@jpshealth.org", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Oumou Kelthoum", lastName: "Med", email: "official.k92@hotmail.com", languages: "Arabic, English, Hassaniya, Gulf Arabic, Egyptian Arabic, Levantine Arabic.", mode2024: "virtual", status2024: "lead" },
  { firstName: "Stephanie", lastName: "Perez Medina", email: "ohstephanie96@gmail.com", languages: "English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Oleh", lastName: "Bilyk", email: "olegbilyk84@gmail.com", languages: "Ukrainian, Russian", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Olenka", lastName: "Davila Mu\u00f1oz", email: "olenka.davila.munoz@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Oscar", lastName: "Bolanos", email: "ombnewyork@live.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Niloofar", lastName: "Omrani", email: "omrani.nelly@gmail.com", languages: "Persian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Orlando", lastName: "Ort\u00edz", email: "orlando.ortiz@swsc.org", languages: "English and Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Ornella", lastName: "Mazzorana", email: "ornellamazzorana@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Omar", lastName: "Zamacona", email: "ozamac1@yahoo.com", languages: "Spanish English", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Gloria", lastName: "Palma", email: "palma.gloria.d@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Paloma", lastName: "Aspe", email: "palomaaspecoding@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Erika", lastName: "Arias", email: "pam06ash@gmail.com", languages: "Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Angelica", lastName: "Paredes", email: "paredes1208@yahoo.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Parirou", lastName: "Djafari", email: "parirou.jafari@gmail.com", languages: "ASL", mode2024: "virtual", status2024: "lead" },
  { firstName: "Dirgha", lastName: "Pathak", email: "pathakdirgha@yahoo.com", languages: "Nepali", mode2024: "virtual", status2024: "lead" },
  { firstName: "Paula", lastName: "Silva Goulart Lopes", email: "paulafabio69@msn.com", languages: "Portuguese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Paulina", lastName: "Martinez", email: "paulinabialas83@gmail.com", languages: "Polish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Paulino", lastName: "Fuentes", email: "Paulino.FuentesJr05@icloud.com", languages: "English and spanush", mode2024: "virtual", status2024: "lead" },
  { firstName: "Patricia", lastName: "Allen", email: "paxallen@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Pedro", lastName: "Medina", email: "Pedro@aalb.org", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Pedro", lastName: "Nevarez", email: "pedron@acutrans.com", languages: "English/Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Peonia", lastName: "Kempenich", email: "pkempenich@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Portia", lastName: "Jones", email: "portia56jones@gmail.com", languages: "English/Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "PAOLO Giuseppe", lastName: "CARUSO", email: "profpaologiuseppecaruso@gmail.com", languages: "Italian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Sanobar", lastName: "Pulatova", email: "psanobar20@gmail.com", languages: "Uzbek,Tajik,Russian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Qiong", lastName: "Hulsey", email: "qhulsey@gmail.com", languages: "Mandarin", mode2024: "virtual", status2024: "paid" },
  { firstName: "Edna Janeth", lastName: "Perez Ortiz", email: "quetzal1105@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Jorge", lastName: "Venereo Tamayo", email: "quimbomb@gmail.com", languages: "Spanish, English, German", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rami", lastName: "Beddiar", email: "rabeddia@med.umich.edu", languages: "Arabic/English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rafael", lastName: "Martinez", email: "rafaelmrtnz7@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rajae", lastName: "Rais", email: "raisrajae@gmail.com", languages: "Arabic", mode2024: "in-person", status2024: "lead" },
  { firstName: "Ramses", lastName: "Monroy Alatorre", email: "ramsesmonroy@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Rania", lastName: "Hamzeh", email: "raniahamzeh13@gmail.com", languages: "Arabic", mode2024: "virtual", status2024: "paid" },
  { firstName: "Ravi", lastName: "Sah", email: "rbsahusa@gmail.com", languages: "Nepali", mode2024: "in-person", status2024: "lead" },
  { firstName: "Roxana", lastName: "Campos", email: "rccampos81@yahoo.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Juan", lastName: "Rosas", email: "redrosas94@ucla.edu", languages: "Engliah", mode2024: "in-person", status2024: "lead" },
  { firstName: "Carolina", lastName: "Leimkuehler", email: "reinabc1990@gmail.com", languages: "Spanish and English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Carlos", lastName: "Larios", email: "return2fury@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Candace", lastName: "Carlson", email: "Rileyc16@mail.lcc.edu", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Lilliam I.", lastName: "Rivera", email: "riveralilliam1877@gmail.com", languages: "English and Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rocio", lastName: "Trevino", email: "rocio.trevino@boostlingo.com", languages: "English and Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Maria", lastName: "Garza", email: "rokioc35@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rooshey", lastName: "Hasnain", email: "roosheyh@uic.edu", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Rose Gabrielle Samuelissa", lastName: "Pierre", email: "rosegabi9897@gmail.com", languages: "French", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rose", lastName: "Samano", email: "rosesamano36@gmail.com", languages: "Assyrian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rosy", lastName: "Encinas", email: "rosyencinas234@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Rosa Isela", lastName: "Mejia Diaz", email: "rosymde@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Roxanna", lastName: "Gomez", email: "roxannagomez001@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Ryan", lastName: "Popma", email: "rpopma89@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Susana", lastName: "Rosas", email: "rsus740@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ryan", lastName: "Maurera", email: "rtmaurera@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ricardo", lastName: "Torres", email: "rtorres@mercy.com", languages: "Spanish &lt;&gt; English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Rub\u00e9n", lastName: "Hern\u00e1ndez", email: "rubenhernandezcastillo81@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Ruby", lastName: "Martinez Gutierrez", email: "rubymartinez264@gmail.com", languages: "spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Carmen", lastName: "Rush", email: "rushcarmen1@gmail.com", languages: "English / Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Roxana", lastName: "Lash", email: "rvlash@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Sadaf", lastName: "Ajani", email: "sadaf.ajani@gmail.com", languages: "English, Urdu, Hindi", mode2024: "virtual", status2024: "lead" },
  { firstName: "Sahal", lastName: "Wais", email: "Sahalnurwacays@gmail.com", languages: "Somali and Amharic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Cici", lastName: "Dashdovdon", email: "sakana388@yahoo.com", languages: "Mongolian", mode2024: "in-person", status2024: "lead" },
  { firstName: "sam", lastName: "cogdell", email: "sam.cogdell@gmail.com", languages: "English, Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Samina", lastName: "Charania", email: "saminacharania@gmail.com", languages: "Urdu Gujarati Hindi", mode2024: "virtual", status2024: "lead" },
  { firstName: "Sandra", lastName: "Abdelnour", email: "sandraashak@gmail.com", languages: "Arabic -English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Sandra", lastName: "Ceballos", email: "sandraceballos87@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Sandy", lastName: "Maloney", email: "sandyvmaloney@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Sarah", lastName: "Blackstone", email: "sarahblack@aol.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Scott", lastName: "Suckow", email: "Scott.Suckow@uchealth.org", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ana", lastName: "Taylor", email: "silvana_taylor1@yahoo.com", languages: "Spanish-English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Silvia", lastName: "Irrazabal", email: "silviairrazabalinterpreting@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Sean", lastName: "Mattews", email: "Smattews@mattlang.us", languages: "Spanish, English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Stoyanka", lastName: "Nikolova", email: "snikolovabs@gmail.com", languages: "Bulgarian, English, German", mode2024: "virtual", status2024: "paid" },
  { firstName: "Sawsan", lastName: "Obeid-Zeki", email: "sobeid2001@hotmail.com", languages: "Arabic", mode2024: "in-person", status2024: "lead" },
  { firstName: "Liliya", lastName: "Sokolova", email: "sokolova.uwm@gmail.com", languages: "Russian", mode2024: "in-person", status2024: "lead" },
  { firstName: "Thomas", lastName: "Powlison", email: "stormwalker.tlp@gmail.com", languages: "Spanish &lt;&gt; English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Susan", lastName: "Freeman", email: "suebfreeman@gmail.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Susana", lastName: "Layug", email: "susanalayug@gmail.com", languages: "Tagalog /Filipino", mode2024: "virtual", status2024: "paid" },
  { firstName: "Susana", lastName: "Liceaga", email: "susyliceaga@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Suyen", lastName: "Averruz", email: "suyen@berkeley.edu", languages: "English, Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Wen-Na", lastName: "Tan", email: "tanandlin@gmail.com", languages: "Chinese-Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Teresa Bel\u00e9n", lastName: "Zepeda", email: "tbzepeda@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Tram", lastName: "Bui", email: "teechedu@gmail.com", languages: "English, Vietnamese", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Te-Ling", lastName: "Hsieh", email: "teling822@gmail.com", languages: "English/Mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "test", lastName: "test", email: "test@test.org", languages: "span", mode2024: "in-person", status2024: "lead" },
  { firstName: "Aakash", lastName: "Thakkar", email: "thakkaraakash@hotmail.com", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Tiffani", lastName: "Ellis", email: "thelanguageexperttme@gmail.com", languages: "English, Portuguese", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Thuhuong", lastName: "Tran", email: "thuhuongtran2015@gmail.com", languages: "Vietnamese", mode2024: "in-person", status2024: "lead" },
  { firstName: "Tiana", lastName: "Boskovich", email: "tianaboskovich@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Trixie Jane", lastName: "Magsino", email: "tjmagsino@gmail.com", languages: "English, tagalog", mode2024: "in-person", status2024: "lead" },
  { firstName: "Thomas", lastName: "Lozano", email: "tjoe232@gmail.com", languages: "Engly", mode2024: "virtual", status2024: "lead" },
  { firstName: "Ty Man", lastName: "Luu", email: "tluu41@mail.ccsf.edu", languages: "Cantonese, Mandarin and Vietnamese", mode2024: "virtual", status2024: "lead" },
  { firstName: "Amelia", lastName: "Smith", email: "translationsbyamelia@gmail.com", languages: "English and Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Tricia", lastName: "Thompson", email: "Tricia.Thompson@ssmhealth.com", languages: "English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Jessica", lastName: "Troche", email: "trochejessica@aol.com", languages: "english", mode2024: "virtual", status2024: "lead" },
  { firstName: "Iman", lastName: "Abukar", email: "tusalaha@gmail.com", languages: "Somali and English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Araminta", lastName: "Hawkins", email: "uspeakiinterpret@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "Veronica", lastName: "Castro", email: "v3ronicacastro@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Valeria", lastName: "Lemus Varela", email: "valeriamik@hotmail.com", languages: "English/Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Valinda", lastName: "Aguirre", email: "valindarodriguez@gmail.com", languages: "English-Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Valoree", lastName: "Boyer", email: "valpbj@gmail.com", languages: "English, ASL", mode2024: "in-person", status2024: "lead" },
  { firstName: "Claudia", lastName: "Mercer", email: "vanillaisclau@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "lead" },
  { firstName: "Victoria", lastName: "Soto", email: "vasoto_00@yahoo.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Vonessa", lastName: "Costa", email: "vcosta@cchicertification.org", languages: "English", mode2024: "in-person", status2024: "lead" },
  { firstName: "Veronica", lastName: "Guemez", email: "vguemez@yahoo.com", languages: "Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Vlada", lastName: "Gazalabova", email: "vgvladlena@gmail.com", languages: "Russian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Victor", lastName: "Robledo", email: "vmrobledo1984@gmail.com", languages: "Spanish, English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Vicky Andrade", lastName: "Nichols", email: "vnichols@ecommunity.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Varsik", lastName: "Sarkisyan", email: "vsb02@yahoo.com", languages: "Russian, Armenian", mode2024: "virtual", status2024: "lead" },
  { firstName: "Veronica", lastName: "Schraeder", email: "vsinterpreter@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "paid" },
  { firstName: "w", lastName: "wang", email: "wenshing.wang@gmail.com", languages: "mandarin", mode2024: "virtual", status2024: "lead" },
  { firstName: "Xane", lastName: "Kimber", email: "xane.kimber@gmail.com", languages: "English, ASL", mode2024: "in-person", status2024: "paid" },
  { firstName: "Ximena", lastName: "Bernal Valencia", email: "ximenabernal1@gmail.com", languages: "Spanish-English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Xochil", lastName: "O'Neill", email: "xochilv@gmail.com", languages: "spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Yasir", lastName: "Osman", email: "yasir.gama@gmail.com", languages: "Arabic", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Yadira", lastName: "Mason", email: "yireneph50@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Young", lastName: "Kwon", email: "ykwon@moia.nyc.gov", languages: "English, Korean", mode2024: "virtual", status2024: "lead" },
  { firstName: "Yaneth", lastName: "Londo\u00f1o", email: "YLONDONOE@GMAIL.COM", languages: "Spanish/English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Yoselyn", lastName: "Julio", email: "Yoselyn_Julio@hotmail.com", languages: "Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Jerrika", lastName: "Velasquez", email: "yourspanishlink@gmail.com", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Yokasta", lastName: "Suero", email: "ysuero@lifespan.org", languages: "Spanish", mode2024: "virtual", status2024: "lead" },
  { firstName: "Irma", lastName: "Yulan", email: "yulanirma@gmail.com", languages: "English", mode2024: "virtual", status2024: "paid" },
  { firstName: "Irma", lastName: "Yulan", email: "yulanirma@yahoo.com", languages: "English and Spanish", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Yesenia", lastName: "Delgado", email: "yyeseniad13@me.com", languages: "Spanish", mode2024: "in-person", status2024: "paid" },
  { firstName: "Zahraa", lastName: "Mushtaq", email: "zahraamushtaq2001@gmail.com", languages: "English/Arabic", mode2024: "virtual", status2024: "lead" },
  { firstName: "Zeeshan", lastName: "Ali", email: "zeeshanali85@gmail.com", languages: "English", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Zecilly", lastName: "Guzman", email: "zeguzman@luriechildrens.org", languages: "English, Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "Zeinab", lastName: "Barud", email: "zeinabbarud@live.com", languages: "Somali", mode2024: "in-person", status2024: "lead" },
  { firstName: "Silvia Roxana", lastName: "Zepeda Moran", email: "zepedarox@gmail.com", languages: "Spanish", mode2024: "in-person", status2024: "lead" },
  { firstName: "ziad", lastName: "turk", email: "ziad_turk@hotmail.com", languages: "Arabic", mode2024: "virtual", status2024: "attempted" },
  { firstName: "Zachary P", lastName: "Romansky", email: "zromansky@luriechildrens.org", languages: "English, Spanish", mode2024: "in-person", status2024: "attempted" },
  { firstName: "Zeinab", lastName: "Al Salman", email: "zs_eng84@yahoo.com", languages: "Arabic", mode2024: "in-person", status2024: "lead" },
];
